<script lang="ts">
	import { PALETTE } from '../sprites';
	import Sprite from '../Sprite.svelte';
	const TOOLS=['Pencil','Erase','Fill','Pick','Select','Move'];
</script>

<div class="mock stage-editor">
	<header><strong>Doodle-Do</strong><div class="modes"><button class="active">Focus</button><button>Grid</button><button>Loop</button></div><input value="chicken-walk" aria-label="Document name"/><span>Saved locally</span><button>Open</button><button class="save">Save</button><button>Export</button></header>
	<div class="work">
		<aside class="frames"><strong>FRAMES</strong>{#each {length:4} as _,i}<button class:current={i===1}><span>0{i+1}</span><Sprite frame={i} scale={4}/><small>{i===1?'160':'113'} ms</small></button>{/each}<button class="add">+</button></aside>
		<main><div class="canvas"><Sprite frame={1} scale={28} onion={0.32} grid/></div><div class="readout"><span>16 × 16</span><b>FRAME 02</b><span>1800%</span></div>
			<div class="layers"><button>Highlights</button><button class="chosen">Chicken</button><button>Rough</button></div>
			<div class="palette"><span>COLOUR</span><button class="alpha" aria-label="Transparent"></button>{#each PALETTE as hex,i}<button class:chosen={i===15} style="background:{hex}" aria-label={hex}></button>{/each}</div>
		</main>
	</div>
	<footer><div class="tools">{#each TOOLS as tool,i}<button class:active={i===0}>{tool}<kbd>{['B','E','G','I','M','V'][i]}</kbd></button>{/each}</div><label>Size <select><option>2 px</option></select></label><button>Mirror</button><button>Flip H</button><button>Flip V</button><label class="onion"><input type="checkbox" checked/> Onion 35%</label><button class="play">▶ Play</button></footer>
</div>

<style>
	.stage-editor{--teal:#173b45;--yellow:#f2d64b;--red:#d8423f;--ink:#151817;display:grid;grid-template-rows:auto minmax(0,1fr) auto;min-height:100vh;background:#dfe4df;color:var(--ink);font:12px/1.35 Archivo,system-ui,sans-serif}button,input,select{min-height:36px;border:1px solid #98a3a1;background:#f7f7f2;color:var(--ink);border-radius:3px}button{padding:.4rem .7rem}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid var(--yellow);outline-offset:2px}header{display:flex;align-items:center;gap:.5rem;padding:.65rem 1rem;background:var(--teal);color:#fff}header strong{font-size:1rem;margin-right:.8rem}.modes{display:flex}.modes button{color:#d7e3e4;background:transparent;border-color:#547078}.modes .active,.save{background:var(--red);color:#fff;border-color:#932c29}header input{width:150px;padding:.4rem .6rem}header>span{margin-left:auto;color:#c3d3d5;font-size:.68rem}header>button{color:#fff;background:transparent;border-color:#547078}
	.work{display:grid;grid-template-columns:104px minmax(0,1fr);min-height:0}.frames{display:flex;flex-direction:column;gap:.5rem;padding:.75rem;background:#eef0eb;border-right:2px solid var(--teal);overflow-y:auto}.frames>strong{font-size:.6rem;letter-spacing:.1em}.frames>button{display:grid;place-items:center;flex:0 0 92px;padding:.25rem;position:relative}.frames button.current{outline:4px solid var(--red);outline-offset:-4px}.frames span{position:absolute;top:5px;left:6px;font-weight:800}.frames small{position:absolute;right:5px;bottom:4px;font-size:.52rem}.frames .add{flex-basis:44px;font-size:1.4rem}
	main{position:relative;min-width:0;padding:1rem 1rem 3.5rem}.canvas{display:grid;place-items:center;width:100%;height:100%;min-height:480px;overflow:hidden;background:repeating-conic-gradient(#e2e2db 0 25%,#fff 0 50%) 0 0/24px 24px;box-shadow:inset 0 0 0 4px var(--teal)}.readout{position:absolute;right:1rem;bottom:1rem;left:1rem;display:flex;justify-content:space-between;padding:.65rem 1rem;background:var(--teal);color:#fff}.layers{position:absolute;top:2rem;left:2rem;display:flex;flex-direction:column;align-items:stretch}.layers button{border-color:var(--teal);border-radius:0}.layers .chosen{background:var(--red);color:#fff}.palette{position:absolute;top:2rem;right:2rem;display:grid;grid-template-columns:repeat(4,28px);gap:4px;padding:.6rem;background:#f7f7f2;box-shadow:0 4px 8px rgba(0,0,0,.18)}.palette span{grid-column:1/-1;font-size:.58rem;font-weight:800}.palette button{min-height:28px;padding:0}.palette button.chosen{outline:3px solid var(--yellow)}.alpha{background:repeating-conic-gradient(#aaa 0 25%,#fff 0 50%) 0 0/8px 8px}
	footer{display:flex;align-items:center;gap:.45rem;padding:.7rem 1rem;background:#f7f7f2;border-top:2px solid var(--teal);overflow-x:auto;white-space:nowrap}.tools{display:flex}.tools button{border-radius:0}.tools .active,.play{background:var(--red);color:#fff;border-color:#932c29}kbd{margin-left:.35rem;font-size:.55rem}footer label{display:flex;align-items:center;gap:.4rem}.onion{margin-left:auto}.onion input{min-height:0}.play{min-width:90px}
	@media(max-width:700px){header input,header>span,header>button:not(.save){display:none}.work{grid-template-columns:1fr;grid-template-rows:86px minmax(0,1fr)}.frames{flex-direction:row;border-right:0;border-bottom:2px solid var(--teal);overflow-x:auto}.frames>strong{display:none}.frames>button{flex:0 0 82px}.frames .add{flex-basis:44px}.canvas{min-height:480px}.canvas :global(canvas){transform:scale(.68)}.layers{top:1.5rem;left:1.5rem}.layers button:not(.chosen){display:none}.palette{top:auto;right:1.5rem;bottom:4.5rem;grid-template-columns:repeat(4,24px)}.palette button{min-height:24px}footer{padding:.5rem}.tools button:nth-child(n+5),footer>button:not(.play),footer>label:not(.onion){display:none}}
</style>
