<script lang="ts">
	import { PALETTE } from '../sprites';
	import Sprite from '../Sprite.svelte';
	const TOOLS=[['Pencil','B'],['Eraser','E'],['Fill','G'],['Pick','I'],['Select','M'],['Lasso','L'],['Wand','W'],['Polygon','P']];
</script>

<div class="mock enamel-shell">
	<header><span class="lamp"></span><strong>Doodle-Do</strong><div class="modes"><button class="on">Focus</button><button>Grid</button><button>Loop</button></div><input value="chicken-walk" aria-label="Document name"/><span class="saved">Saved locally</span><div class="files"><button>New</button><button>Open</button><button class="save">Save</button><button>Export</button></div></header>
	<div class="toolbar"><div class="tools">{#each TOOLS as [name,key]}<button class:on={name==='Pencil'}>{name}<kbd>{key}</kbd></button>{/each}</div><label>Brush <select><option>2 px</option></select></label><button>Mirror</button><button>Flip H</button><button>Flip V</button><button class="onion">Onion</button><input type="range" value="35" aria-label="Onion opacity"/><span>35%</span></div>
	<div class="work"><main><div class="screen"><Sprite frame={1} scale={24} onion={0.35} grid/></div><div class="status"><span>Frame 02 of 04</span><span>16 × 16</span><span><i class="prev"></i>Previous</span><span><i class="next"></i>Next</span><span class="zoom">− <b>1800%</b> +</span></div></main><aside><section><div class="section-head"><h2>Live inspection</h2><span>● 8 fps</span></div><div class="preview"><Sprite playing scale={7}/></div><dl><div><dt>Frames</dt><dd>4</dd></div><div><dt>Cycle</dt><dd>500 ms</dd></div></dl></section><section><div class="section-head"><h2>Layers</h2><button>+</button></div><ul><li>● <span>highlights</span><button>•••</button></li><li class="active">● <span>chicken</span><button>•••</button></li><li>○ <span>rough</span><button>•••</button></li></ul><button class="wide">Merge down</button></section><section><div class="section-head"><h2>Palette <small>16 / 64</small></h2><button class="locked">Locked</button></div><div class="palette"><button class="sw alpha" aria-label="Transparent"></button>{#each PALETTE as hex,i}<button class="sw" class:sel={i===15} style="background:{hex}" aria-label={hex}></button>{/each}</div></section></aside></div>
	<footer><div class="frame-head"><strong>Frames</strong><button>New</button><button>Duplicate</button><button>Delete</button><span>Loop 01 → 04</span><label>Hold <input value="125"/> ms</label></div><ol>{#each {length:10} as _,i}<li><button class:current={i===1}>{#if i<4}<Sprite frame={i} scale={4}/>{:else}<b>+</b>{/if}</button><span>{String(i+1).padStart(2,'0')}</span></li>{/each}</ol></footer>
	<div class="tip"><i></i><b>T02</b><p>The red ghost is your previous frame. Draw where things moved to, not where they were.</p><button>×</button></div>
</div>

<style>
	.enamel-shell{--white:#f7f8f4;--blue:#18577d;--blue-dark:#103b55;--ink:#1d2a30;--muted:#59676c;--red:#a92e28;--yellow:#e7bd31;--line:#9fb5bf;display:flex;flex-direction:column;min-height:100vh;background:#dbe5e8;color:var(--ink);font:13px/1.4 Archivo,system-ui,sans-serif}button,input,select{min-height:29px;color:var(--ink);background:var(--white);border:1px solid var(--line);border-radius:4px}button{padding:.25rem .55rem}button:hover{background:#fff}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid var(--yellow);outline-offset:1px}
	header{display:flex;align-items:center;gap:.7rem;min-height:54px;padding:.55rem .8rem;color:#fff;background:var(--blue);border-bottom:4px solid var(--blue-dark)}header>.lamp{width:12px;height:12px;background:var(--yellow);border:2px solid #8d741d;border-radius:50%}.modes{display:flex}.modes button{color:#e5f0f4;background:transparent;border-color:#4d7890;border-radius:0;margin-left:-1px}.modes button:first-child{border-radius:4px 0 0 4px}.modes button:last-child{border-radius:0 4px 4px 0}.modes .on,.save{color:#fff;background:var(--red);border-color:#7d1c18}header>input{width:165px;padding:.35rem}.saved{margin-left:auto;color:#c9dde6;font-size:.66rem}.files{display:flex;gap:.3rem}
	.toolbar{display:flex;align-items:center;gap:.4rem;padding:.45rem .8rem;background:var(--white);border-bottom:2px solid var(--blue);overflow-x:auto;white-space:nowrap}.tools{display:flex}.tools button{border-radius:0;margin-left:-1px}.tools button:first-child{border-radius:4px 0 0 4px}.tools button:last-child{border-radius:0 4px 4px 0}.tools .on,.onion{color:#fff;background:var(--blue);border-color:var(--blue)}kbd{margin-left:.25rem;font-size:.56rem}.toolbar label{display:flex;align-items:center;gap:.3rem;color:var(--muted)}.toolbar select{padding:.2rem}.toolbar input[type=range]{width:82px;accent-color:var(--red)}
	.work{display:grid;grid-template-columns:minmax(420px,1fr) 260px;flex:1;min-height:470px}.work main{display:flex;flex-direction:column;min-width:0;padding:1rem}.screen{display:grid;place-items:center;flex:1;min-height:420px;background:repeating-conic-gradient(#e1e5e2 0 25%,#fff 0 50%) 0 0/20px 20px;border:4px solid var(--blue);border-radius:12px;box-shadow:inset 0 0 0 4px #fff}.status{display:flex;gap:1rem;padding:.5rem .25rem 0;color:#44585f;font-size:.66rem}.status i{display:inline-block;width:9px;height:9px;margin-right:.3rem;border-radius:2px}.prev{background:#d04648}.next{background:#6daa2c}.zoom{margin-left:auto}.zoom b{color:var(--ink);margin:0 .5rem}
	aside{background:var(--white);border-left:3px solid var(--blue)}aside section{padding:.75rem;border-bottom:3px solid var(--blue)}.section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:.55rem}.section-head h2{font-size:.78rem;color:var(--blue)}.section-head span{color:var(--red);font-size:.62rem}.section-head small{color:var(--muted)}.section-head button{min-height:23px;padding:.1rem .35rem}.preview{display:grid;place-items:center;aspect-ratio:1.6;background:#fff;border:2px solid var(--blue);border-radius:7px}dl{margin:0}dl div{display:flex;justify-content:space-between;padding:.3rem 0;border-bottom:1px solid var(--line);font-size:.65rem}dt{color:var(--muted)}dd{margin:0;font-weight:700}aside ul{border-top:1px solid var(--line)}aside li{display:grid;grid-template-columns:auto 1fr auto;align-items:center;padding:.3rem;color:var(--blue);border-bottom:1px solid var(--line)}aside li.active{color:var(--red);background:#f2dcd8}aside li button{min-height:22px;padding:.1rem .3rem;border:0;background:transparent}.wide{width:100%;margin-top:.5rem}.locked{color:var(--red)!important}.palette{display:grid;grid-template-columns:repeat(6,1fr);gap:5px}.sw{aspect-ratio:1;min-height:0;padding:0;border-radius:4px}.alpha{background:repeating-conic-gradient(#bfc8c8 0 25%,#fff 0 50%) 0 0/8px 8px}.sw.sel{outline:3px solid var(--red);outline-offset:1px}
	footer{background:var(--white);border-top:3px solid var(--blue)}.frame-head{display:flex;align-items:center;gap:.4rem;padding:.4rem .7rem;border-bottom:1px solid var(--line)}.frame-head span{margin-left:auto;color:var(--muted)}.frame-head label{color:var(--muted)}.frame-head input{width:44px;padding:.2rem;text-align:right}footer ol{display:flex;gap:.45rem;padding:.45rem .7rem!important;overflow-x:auto}footer li{flex:0 0 58px;text-align:center;color:var(--muted);font-size:.58rem}footer li button{display:grid;place-items:center;width:58px;aspect-ratio:1;padding:0;background:#fff;border:2px solid var(--blue)}footer li button.current{outline:3px solid var(--red);outline-offset:1px}footer li b{color:#8ca0a8}
	.tip{position:fixed;right:280px;bottom:154px;display:grid;grid-template-columns:auto auto minmax(240px,420px) auto;align-items:center;gap:.7rem;padding:.7rem .85rem;color:#fff;background:var(--blue);border-radius:6px}.tip i{width:12px;height:12px;background:var(--yellow);border-radius:50%}.tip b{font-size:.65rem}.tip p{font-size:.75rem}.tip button{color:#fff;border:0;background:transparent}
	@media(max-width:900px){.work{grid-template-columns:1fr}aside{display:grid;grid-template-columns:repeat(3,1fr);border-left:0;border-top:3px solid var(--blue)}.tip{display:none}}
	@media(max-width:680px){header{flex-wrap:wrap}.saved,header>input{display:none}.files{margin-left:auto}.files button:not(.save){display:none}.tools button:nth-child(n+5),.toolbar>button,.toolbar>label,.toolbar>input,.toolbar>span{display:none}.work main{padding:.55rem}.screen{min-height:55vh}aside{grid-template-columns:1fr}.frame-head button:nth-of-type(n+2),.frame-head span{display:none}.status span:nth-child(3),.status span:nth-child(4){display:none}}
</style>
