<script lang="ts">
	import Sprite from '../Sprite.svelte';
	const VIEWS=[['1','Focus','Drawing one frame','Comparing the sequence'],['2','Grid','Editing all frames','Working at pixel scale'],['3','Loop','Judging the motion','Making a new mark']];
</script>

<div class="mock enamel-page">
	<header><a class="mark" href="#top"><span></span>Doodle-Do</a><nav><a href="#bench">Workbench</a><a href="#views">Views</a><a href="#out">Output</a></nav><a class="red-key" href="#top">Start drawing</a></header>
	<main id="top">
		<section class="hero">
			<div class="pitch"><p class="plate-no">Workbench 01 · live animation</p><h1>Draw the chicken.<br/>Check the motion.</h1><p>Pixel animation in the browser with playback that stays on, practical teaching notes, and engine-ready export.</p><div class="actions"><a class="red-key big" href="#bench">Start drawing</a><a href="#out">See the output →</a></div><small>No account · no upload · works offline</small></div>
			<div class="machine"><i class="bolt tl"></i><i class="bolt tr"></i><i class="bolt bl"></i><i class="bolt br"></i><div class="machine-head"><span>LIVE INSPECTION</span><b>8 FPS</b><em>● RUNNING</em></div><div class="display"><Sprite playing scale={18}/></div><ol>{#each {length:8} as _,i}<li class:on={i<4} class:now={i===1}>{#if i<4}<Sprite frame={i} scale={3}/>{:else}<span>{i+1}</span>{/if}</li>{/each}</ol><div class="machine-foot"><span>4 FRAMES</span><span>500 MS LOOP</span><span>16 × 16</span></div></div>
		</section>

		<section class="bench" id="bench"><div class="section-copy"><p>Inspection 01</p><h2>The loop stays under your hand.</h2><span>Every stroke lands in moving context. Holds, weak silhouettes, and uneven spacing show themselves immediately.</span></div><div class="sequence">{#each {length:4} as _,i}<figure><span>F{i+1}</span><div><Sprite frame={i} scale={8}/></div><figcaption>{i===1?'160':'113'} ms</figcaption></figure>{/each}<div class="lamp"><i></i><b>PASS</b><span>loop reads clearly</span></div></div></section>

		<section class="views" id="views"><div class="section-copy"><p>Inspection 02</p><h2>Three fixtures, one document.</h2><span>Switch views without moving the frame, palette, zoom, or history. Each panel names its blind spot.</span></div><div class="view-bank"><div class="labels"><span>Key</span><span>View</span><span>Great at</span><span>Strains when</span></div>{#each VIEWS as [key,name,great,bad]}<div><kbd>{key}</kbd><strong>{name}</strong><span>{great}</span><em>{bad}</em></div>{/each}</div></section>

		<section class="lesson"><div class="yellow-lamp"></div><b>T02</b><blockquote>The red ghost is your previous frame. Draw where things moved to, not where they were.</blockquote><p>One relevant note at a time. Dismiss any note forever.</p></section>

		<section class="out" id="out"><div class="section-copy"><p>Rear fittings</p><h2>Standard files leave the bench.</h2><span>PNG sheet, TexturePacker JSON, Doodle-Do project, GIF, or zipped frames. Phaser and Godot compatibility is verified.</span></div><div class="ports"><div><i></i><b>SHEET</b><span>PNG</span></div><div><i></i><b>ATLAS</b><span>JSON</span></div><div><i></i><b>PROJECT</b><span>DOODLEDO</span></div><div><i></i><b>PREVIEW</b><span>GIF</span></div></div></section>
	</main>
	<footer><span class="mark"><i></i>Doodle-Do</span><p>16 colours to start · 64 max · 1-bit alpha · Canvas 2D</p><a class="red-key" href="#top">Start drawing</a></footer>
</div>

<style>
	.enamel-page{--white:#f7f8f4;--blue:#18577d;--blue-dark:#103b55;--ink:#1d2a30;--muted:#59676c;--red:#a92e28;--yellow:#e7bd31;--line:#9fb5bf;min-height:100%;background:var(--white);color:var(--ink);font:16px/1.55 Archivo,system-ui,sans-serif}a{color:inherit}header{display:flex;align-items:center;gap:2rem;padding:1rem clamp(1rem,5vw,5rem);color:#fff;background:var(--blue);border-bottom:5px solid var(--blue-dark)}.mark{display:flex;align-items:center;gap:.6rem;margin-right:auto;font-weight:800;text-decoration:none}.mark>span,.mark>i{width:12px;height:12px;background:var(--red);border:3px solid #fff;border-radius:50%}header nav{display:flex;gap:1.5rem}header nav a{color:#dceaf0;font-size:.8rem;text-decoration:none}.red-key{display:inline-flex;align-items:center;justify-content:center;min-height:40px;padding:.45rem 1rem;color:#fff;background:var(--red);border:2px solid #7d1c18;border-radius:5px;font-weight:800;text-decoration:none;box-shadow:inset 0 1px 0 rgba(255,255,255,.32)}.red-key:hover{background:#c23a33}.red-key:focus-visible,a:focus-visible{outline:3px solid var(--yellow);outline-offset:2px}
	main,footer{width:min(1160px,calc(100% - 2rem));margin:auto}.hero{display:grid;grid-template-columns:minmax(280px,.75fr) minmax(510px,1.25fr);align-items:center;gap:clamp(3rem,7vw,7rem);min-height:720px;padding:4rem 0}.plate-no,.section-copy>p{color:var(--blue);font-size:.68rem;font-weight:800;letter-spacing:.13em;text-transform:uppercase}.pitch h1{max-width:11ch;margin-top:1rem!important;font-size:clamp(3rem,5.3vw,5.2rem);line-height:.96;letter-spacing:-.04em;text-wrap:balance}.pitch>p:not(.plate-no){max-width:40ch;margin-top:1.5rem;color:var(--muted);font-size:1.08rem}.actions{display:flex;align-items:center;gap:1.2rem;margin-top:1.8rem}.actions>a:last-child{color:var(--blue);font-size:.86rem;font-weight:700;text-decoration:none}.big{min-height:48px;padding:.65rem 1.2rem}.pitch small{display:block;margin-top:1.2rem;color:#68767b}
	.machine{position:relative;padding:1rem;background:#eef1ee;border:4px solid var(--blue);border-radius:14px;box-shadow:inset 0 0 0 4px #fff,0 7px 12px rgba(25,66,87,.18)}.bolt{position:absolute;width:10px;height:10px;background:#75868d;border-radius:50%}.tl{top:8px;left:8px}.tr{top:8px;right:8px}.bl{bottom:8px;left:8px}.br{bottom:8px;right:8px}.machine-head,.machine-foot{display:flex;justify-content:space-between;padding:.6rem 1.1rem;color:var(--blue-dark);font-size:.62rem;font-weight:800;letter-spacing:.08em}.machine-head em{color:#8b241f;font-style:normal}.display{display:grid;place-items:center;min-height:360px;background:repeating-conic-gradient(#e1e5e2 0 25%,#fff 0 50%) 0 0/18px 18px;border:3px solid var(--blue-dark);border-radius:7px}.machine ol{display:grid;grid-template-columns:repeat(8,1fr);gap:7px;margin-top:.7rem!important}.machine li{display:grid;place-items:center;aspect-ratio:1;color:#7d898d;background:#d7ddda;border:2px solid #abb9be;border-radius:6px;font-size:.6rem}.machine li.on{background:#fff}.machine li.now{outline:3px solid var(--red);outline-offset:1px}
	section:not(.hero){display:grid;grid-template-columns:minmax(230px,.55fr) minmax(470px,1fr);gap:clamp(2rem,8vw,7rem);padding:clamp(4rem,9vw,8rem) 0;border-top:3px solid var(--blue)}.section-copy h2{max-width:14ch;margin-top:.8rem!important;font-size:clamp(2rem,3.5vw,3rem);line-height:1.05;letter-spacing:-.035em;text-wrap:balance}.section-copy>span{display:block;max-width:40ch;margin-top:1rem;color:var(--muted)}
	.sequence{display:grid;grid-template-columns:repeat(4,1fr) 105px;gap:8px}.sequence figure{border:2px solid var(--blue);border-radius:6px;overflow:hidden}.sequence figure>span{display:block;padding:.3rem .45rem;color:#fff;background:var(--blue);font-size:.62rem;font-weight:800}.sequence figure>div{display:grid;place-items:center;aspect-ratio:1;background:#fff}.sequence figcaption{padding:.35rem .45rem;color:var(--muted);font-size:.62rem;text-align:right}.lamp{display:flex;flex-direction:column;align-items:center;justify-content:center;color:#fff;background:var(--blue);border-radius:7px}.lamp i,.yellow-lamp{width:16px;height:16px;background:var(--yellow);border:3px solid #8d741d;border-radius:50%;box-shadow:0 0 7px rgba(231,189,49,.75)}.lamp b{margin-top:.7rem}.lamp span{font-size:.55rem}
	.view-bank{border:3px solid var(--blue);border-radius:7px;overflow:hidden}.labels,.view-bank>div{display:grid;grid-template-columns:45px 90px 1fr 1fr;gap:1rem;align-items:center;padding:.8rem}.labels{color:#dceaf0;background:var(--blue);font-size:.62rem;font-weight:700}.view-bank>div:not(.labels){border-top:1px solid var(--line)}.view-bank kbd{display:grid;place-items:center;width:28px;height:28px;color:#fff;background:var(--red);border-radius:4px;font:700 .7rem/1 Archivo,sans-serif}.view-bank span,.view-bank em{font-size:.82rem}.view-bank em{color:#814740;font-style:normal}
	.lesson{grid-template-columns:24px 46px minmax(300px,1fr) minmax(180px,.4fr)!important;align-items:center;padding:2.5rem!important;color:#fff;background:var(--blue);border:0!important;border-radius:8px}.lesson b{color:#fff}.lesson blockquote{margin:0;font-size:1.3rem;line-height:1.35}.lesson p{color:#d2e2e8;font-size:.78rem}
	.ports{display:grid;grid-template-columns:repeat(4,1fr);border:3px solid var(--blue);border-radius:7px;overflow:hidden}.ports div{display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:170px;border-left:1px solid var(--line)}.ports div:first-child{border:0}.ports i{width:38px;height:38px;background:var(--blue-dark);border:8px solid #bdcbd0;border-radius:50%;box-shadow:inset 0 0 0 5px #071b25}.ports b{margin-top:.8rem;color:var(--blue)}.ports span{color:var(--muted);font-size:.62rem}
	footer{display:flex;align-items:center;gap:1.2rem;padding:3rem 0 9rem;border-top:3px solid var(--blue)}footer .mark{margin:0}footer p{margin-right:auto!important;color:var(--muted);font-size:.72rem}
	@media(max-width:850px){.hero,section:not(.hero){grid-template-columns:1fr}.hero{min-height:0}.hero>*{min-width:0}.machine{width:100%;max-width:100%;margin-top:1rem;overflow:hidden}.machine ol{grid-template-columns:repeat(8,minmax(0,1fr))}.lesson{grid-template-columns:24px 40px 1fr!important}.lesson p{grid-column:3}}
	@media(max-width:620px){header nav{display:none}.display{min-height:280px}.sequence{grid-template-columns:repeat(4,1fr)}.lamp{grid-column:1/-1;min-height:75px}.labels{display:none}.view-bank>div{grid-template-columns:38px 1fr}.view-bank span,.view-bank em{grid-column:2}.ports{grid-template-columns:repeat(2,1fr)}.ports div:nth-child(3){border-left:0;border-top:1px solid var(--line)}.ports div:nth-child(4){border-top:1px solid var(--line)}footer{flex-wrap:wrap}footer p{width:100%}}
</style>
