<script lang="ts">
	import { PALETTE } from '../sprites';
	import Sprite from '../Sprite.svelte';
	const TOOLS=[['Pencil','B'],['Eraser','E'],['Fill','G'],['Pick','I'],['Select','M'],['Lasso','L'],['Wand','W'],['Polygon','P']];
</script>

<div class="mock cart-shell"><header><strong>DOODLE-DO</strong><span>SPRITE KIT</span><div class="modes"><button class="on">FOCUS 1</button><button>GRID 2</button><button>LOOP 3</button></div><input value="chicken-walk" aria-label="Document name"/><i>SAVED LOCAL</i><div class="files"><button>NEW</button><button>OPEN</button><button class="save">SAVE</button><button>EXPORT</button></div></header><div class="toolbar"><div class="tools">{#each TOOLS as [name,key]}<button class:on={name==='Pencil'}>{name.toUpperCase()} <kbd>{key}</kbd></button>{/each}</div><label>BRUSH <select><option>2 PX</option></select></label><button>MIRROR</button><button>FLIP H</button><button>FLIP V</button><button class="onion">ONION</button><input type="range" value="35" aria-label="Onion opacity"/><span>35%</span></div>
	<div class="middle"><main><div class="screen"><div class="screen-head">ROM PREVIEW / FRAME 02</div><div class="canvas"><Sprite frame={1} scale={24} onion={0.35} grid/></div><div class="screen-foot"><span>16 × 16</span><span>DB16</span><span>1-BIT ALPHA</span></div></div><div class="status"><span><i class="prev"></i>PREVIOUS</span><span><i class="next"></i>NEXT</span><span class="zoom">− <b>1800%</b> +</span></div></main><aside><section><div class="section-head"><h2>LIVE ROM</h2><span>08 FPS</span></div><div class="preview"><Sprite playing scale={7}/></div><dl><div><dt>FRAMES</dt><dd>04</dd></div><div><dt>CYCLE</dt><dd>500 MS</dd></div></dl></section><section><div class="section-head"><h2>LAYER BANK</h2><button>+</button></div><ul><li>● <span>HIGHLIGHTS</span><button>•••</button></li><li class="active">● <span>CHICKEN</span><button>•••</button></li><li>○ <span>ROUGH</span><button>•••</button></li></ul><button class="wide">MERGE DOWN</button></section><section><div class="section-head"><h2>COLOUR ROM</h2><button class="locked">LOCKED</button></div><div class="palette"><button class="sw alpha" aria-label="Transparent"></button>{#each PALETTE as hex,i}<button class="sw" class:sel={i===15} style="background:{hex}" aria-label={hex}></button>{/each}</div></section></aside></div>
	<footer><div class="frame-head"><strong>FRAME ADDRESSES</strong><button>NEW</button><button>DUPLICATE</button><button>DELETE</button><span>LOOP 00 → 03</span><label>HOLD <input value="125"/> MS</label></div><ol>{#each {length:10} as _,i}<li><span>0{i.toString(16).toUpperCase()}</span><button class:current={i===1}>{#if i<4}<Sprite frame={i} scale={4}/>{:else}<b>+</b>{/if}</button></li>{/each}</ol></footer><div class="tip"><b>T10</b><p>A TIGHT FOUR-FRAME LOOP OFTEN READS BETTER THAN A LOOSE EIGHT. THE LOOP PREVIEW NEVER LIES.</p><button>×</button></div></div>

<style>
	.cart-shell{--navy:#171a2b;--navy2:#0f1120;--indigo:#3f49b5;--paper:#f1f0e8;--red:#bd3936;--yellow:#e2bd45;--line:#85899d;display:flex;flex-direction:column;min-height:100vh;background:var(--navy);color:#fff;font:12px/1.4 Archivo,system-ui,sans-serif}button,input,select{min-height:29px;color:#fff;background:var(--navy);border:1px solid var(--line);border-radius:3px}button{padding:.25rem .5rem}button:hover{background:#2b2f45}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid var(--yellow);outline-offset:1px}header{display:flex;align-items:center;gap:.65rem;min-height:54px;padding:.55rem .75rem;background:var(--navy2);border-bottom:2px solid var(--indigo)}header>span{color:#9ea3c6;font-size:.58rem}.modes{display:flex}.modes button{margin-left:-1px}.modes .on,.save{background:var(--red);border-color:#7e2422}header>input{width:155px;padding:.35rem;color:#171a2b;background:var(--paper)}header>i{margin-left:auto;color:#aeb5d5;font-size:.56rem;font-style:normal}.files{display:flex;gap:.3rem}
	.toolbar{display:flex;align-items:center;gap:.35rem;padding:.45rem .75rem;background:#22263a;border-bottom:1px solid var(--line);overflow-x:auto;white-space:nowrap}.tools{display:flex}.tools button{margin-left:-1px}.tools .on,.onion{background:var(--indigo);border-color:#7078d6}kbd{font-size:.52rem}.toolbar label{display:flex;align-items:center;gap:.3rem;color:#b6bad0;font-size:.56rem}.toolbar select{padding:.2rem}.toolbar input[type=range]{width:80px;accent-color:var(--red)}
	.middle{display:grid;grid-template-columns:minmax(420px,1fr) 260px;flex:1;min-height:470px}.middle main{display:flex;flex-direction:column;min-width:0;padding:1rem;background:#24283d}.screen{display:flex;flex-direction:column;flex:1;min-height:430px;background:var(--paper);border:4px solid var(--indigo);border-radius:8px;box-shadow:inset 0 0 0 4px var(--navy)}.screen-head,.screen-foot{display:flex;justify-content:space-between;padding:.55rem .7rem;color:#fff;background:var(--indigo);font-size:.58rem;font-weight:700}.canvas{display:grid;place-items:center;flex:1;overflow:hidden;background:repeating-conic-gradient(#dfded7 0 25%,#fff 0 50%) 0 0/20px 20px}.status{display:flex;gap:1rem;padding:.5rem .25rem 0;color:#bdc1d8;font-size:.56rem}.status i{display:inline-block;width:9px;height:9px;margin-right:.3rem}.prev{background:#d04648}.next{background:#6daa2c}.zoom{margin-left:auto}.zoom b{margin:0 .5rem;color:#fff}
	aside{background:var(--navy2);border-left:2px solid var(--indigo)}aside section{padding:.7rem;border-bottom:2px solid var(--indigo)}.section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:.5rem}.section-head h2{font-size:.64rem}.section-head span{color:#ef6b66;font-size:.56rem}.section-head button{min-height:22px;padding:.1rem .3rem}.preview{display:grid;place-items:center;aspect-ratio:1.6;background:#22263a;border:1px solid var(--line)}dl{margin:0}dl div{display:flex;justify-content:space-between;padding:.3rem 0;border-bottom:1px solid #474b61;font-size:.56rem}dt{color:#a4a9c2}dd{margin:0}aside ul{border-top:1px solid #474b61}aside li{display:grid;grid-template-columns:auto 1fr auto;align-items:center;padding:.3rem;color:#b7bbd1;border-bottom:1px solid #474b61;font-size:.56rem}aside li.active{color:#fff;background:var(--indigo)}aside li button{min-height:21px;padding:.1rem .3rem;border:0;background:transparent}.wide{width:100%;margin-top:.5rem}.locked{background:var(--red)!important}.palette{display:grid;grid-template-columns:repeat(6,1fr);gap:4px}.sw{aspect-ratio:1;min-height:0;padding:0}.alpha{background:repeating-conic-gradient(#565a6f 0 25%,#d9d9dc 0 50%) 0 0/8px 8px}.sw.sel{outline:2px solid var(--yellow);outline-offset:1px}
	footer{background:var(--navy2);border-top:2px solid var(--indigo)}.frame-head{display:flex;align-items:center;gap:.4rem;padding:.4rem .7rem;border-bottom:1px solid #474b61;font-size:.56rem}.frame-head span{margin-left:auto}.frame-head input{width:42px;padding:.2rem;color:var(--navy);background:var(--paper)}footer ol{display:flex;gap:.4rem;padding:.45rem .7rem!important;overflow-x:auto}footer li{flex:0 0 58px;text-align:center;color:#a8acc4;font-size:.52rem}footer li button{display:grid;place-items:center;width:58px;aspect-ratio:1;padding:0;background:#22263a}footer li button.current{outline:2px solid var(--red);outline-offset:1px}footer li b{color:#6f748d}
	.tip{position:fixed;right:280px;bottom:154px;display:grid;grid-template-columns:auto minmax(260px,430px) auto;align-items:center;gap:.7rem;padding:.7rem .85rem;color:#171a2b;background:var(--paper);border:3px solid var(--red)}.tip b{color:var(--red)}.tip p{font-size:.58rem}.tip button{color:#171a2b;border:0;background:transparent}
	@media(max-width:900px){.middle{grid-template-columns:1fr}aside{display:grid;grid-template-columns:repeat(3,1fr);border-left:0;border-top:2px solid var(--indigo)}.tip{display:none}}
	@media(max-width:680px){header{flex-wrap:wrap}header>span,header>i,header>input{display:none}.files{margin-left:auto}.files button:not(.save){display:none}.tools button:nth-child(n+5),.toolbar>button,.toolbar>label,.toolbar>input,.toolbar>span{display:none}.middle main{padding:.55rem}.canvas :global(canvas){transform:scale(.84)}aside{grid-template-columns:1fr}.frame-head button:nth-of-type(n+2),.frame-head span{display:none}}
</style>
