<script lang="ts">
	import Sprite from '../Sprite.svelte';
	const MODES=[['1','Focus','Draw one frame with onion context.','Comparing the complete run.'],['2','Grid','Edit every pose side by side.','Fine pixel work.'],['3','Loop','Judge motion at game speed.','Making a new mark.']];
</script>

<div class="mock cart-page">
	<header><a class="brand" href="#top">DOODLE-DO <span>SPRITE KIT</span></a><nav><a href="#build">Build</a><a href="#views">Views</a><a href="#ship">Ship</a></nav><a class="button" href="#top">Open editor</a></header>
	<main id="top">
		<section class="hero"><div class="pitch"><p>Game asset utility · local cartridge 001</p><h1>Make the sprite.<br/>Ship the game.</h1><span>Draw a frame-by-frame loop in the browser, learn timing while it moves, then export files your engine already understands.</span><div class="actions"><a class="button big" href="#build">Start drawing</a><a href="#ship">See engine output →</a></div><small>No account · no upload · works offline</small></div>
			<div class="cartridge"><i class="screw s1"></i><i class="screw s2"></i><div class="ridge"></div><div class="label"><div class="label-head"><b>DOODLE-DO</b><span>CHICKEN WALK / 4F</span></div><div class="screen"><Sprite playing scale={16}/></div><div class="label-foot"><span>8 FPS</span><span>16 × 16</span><span>DB16</span></div></div><div class="contacts">{#each {length:14} as _}<i></i>{/each}</div></div>
		</section>

		<section id="build"><div class="section-copy"><p>Build 01 · animation ROM</p><h2>Four poses become one playable loop.</h2><span>Playback stays on while you edit. Timing, silhouette, and weak spacing show up before the asset reaches a scene.</span></div><div class="frame-rom">{#each {length:4} as _,i}<figure><header><b>ADDR 0{i}</b><span>{i===1?'160':'113'} MS</span></header><div><Sprite frame={i} scale={8}/></div><figcaption>FRAME {i+1} / 4</figcaption></figure>{/each}<div class="play"><span>▶</span><b>8 FPS</b><small>500 MS</small></div></div></section>

		<section id="views"><div class="section-copy"><p>Build 02 · view bank</p><h2>Three tools around the same save state.</h2><span>Frame, zoom, palette, and undo history follow each switch. Every view lists its weak use case.</span></div><div class="mode-table"><div class="head"><span>Key</span><span>View</span><span>Best use</span><span>Avoid when</span></div>{#each MODES as [key,name,great,bad]}<div><kbd>{key}</kbd><strong>{name}</strong><span>{great}</span><em>{bad}</em></div>{/each}</div></section>

		<section class="tip"><b>TIP ROM / T10</b><blockquote>A tight four-frame loop often reads better than a loose eight. The loop preview never lies.</blockquote><p>Contextual notes arrive after relevant actions and can be switched off one by one.</p></section>

		<section id="ship"><div class="section-copy"><p>Build 03 · output ports</p><h2>Drop the finished asset into the engine.</h2><span>Sprite sheet and TexturePacker atlas export are verified against stock Phaser and Godot.</span></div><div class="files"><div><b>PNG</b><span>SPRITE SHEET</span><small>uniform grid</small></div><div><b>JSON</b><span>ATLAS DATA</span><small>engine import</small></div><div><b>DOODLEDO</b><span>PROJECT</span><small>owned source</small></div><div><b>GIF / ZIP</b><span>PREVIEW / FRAMES</span><small>share or unpack</small></div></div></section>
	</main>
	<footer><strong>DOODLE-DO SPRITE KIT</strong><p>16 COLOURS · 64 MAX · 1-BIT ALPHA · CANVAS 2D</p><a class="button" href="#top">Open editor</a></footer>
</div>

<style>
	.cart-page{--navy:#171a2b;--navy2:#0f1120;--indigo:#3f49b5;--paper:#f1f0e8;--ink:#1c2030;--red:#bd3936;--yellow:#e2bd45;--line:#a5a7b5;min-height:100%;background:var(--paper);color:var(--ink);font:15px/1.55 Archivo,system-ui,sans-serif}a{color:inherit}header{display:flex;align-items:center;gap:2rem;padding:1rem clamp(1rem,5vw,5rem);color:#fff;background:var(--navy)}.brand{margin-right:auto;font-weight:800;text-decoration:none}.brand span{margin-left:.6rem;color:#a8acd0;font-size:.62rem}header nav{display:flex;gap:1.5rem}header nav a{color:#ced0e5;font-size:.78rem;text-decoration:none}.button{display:inline-flex;align-items:center;justify-content:center;min-height:40px;padding:.45rem 1rem;color:#fff;background:var(--red);border:2px solid #7e2422;border-radius:4px;font-weight:800;text-decoration:none}.button:hover{background:#d94d48}.button:focus-visible,a:focus-visible{outline:3px solid var(--yellow);outline-offset:2px}
	main,footer{width:min(1160px,calc(100% - 2rem));margin:auto}.hero{display:grid;grid-template-columns:minmax(280px,.76fr) minmax(500px,1.24fr);align-items:center;gap:clamp(3rem,8vw,8rem);min-height:720px;padding:4rem 0}.pitch>p,.section-copy>p{color:var(--indigo);font-size:.68rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.pitch h1{max-width:11ch;margin-top:1rem!important;font-size:clamp(3rem,5.5vw,5.3rem);line-height:.96;letter-spacing:-.04em;text-wrap:balance}.pitch>span{display:block;max-width:41ch;margin-top:1.5rem;color:#565b6b;font-size:1.05rem}.actions{display:flex;align-items:center;gap:1.2rem;margin-top:1.8rem}.actions>a:last-child{color:var(--indigo);font-size:.86rem;font-weight:700;text-decoration:none}.big{min-height:48px;padding:.65rem 1.2rem}.pitch small{display:block;margin-top:1.2rem;color:#666a78}
	.cartridge{position:relative;width:min(100%,560px);min-height:520px;margin:auto;padding:5.2rem 4rem 4.8rem;background:var(--navy);border:4px solid var(--navy2);border-radius:15px 15px 6px 6px;box-shadow:inset 0 2px 0 #36394e,0 8px 14px rgba(16,18,31,.22)}.ridge{position:absolute;top:24px;left:16%;width:68%;height:28px;border-top:5px solid #2d3146;border-bottom:5px solid #0b0d18}.screw{position:absolute;width:12px;height:12px;background:#565a6d;border:2px solid #090a10;border-radius:50%}.s1{top:28px;left:28px}.s2{top:28px;right:28px}.label{background:var(--paper);border:4px solid var(--indigo);border-radius:8px;overflow:hidden}.label-head,.label-foot{display:flex;justify-content:space-between;padding:.65rem .8rem;font-size:.58rem;font-weight:800}.label-head{color:#fff;background:var(--indigo)}.screen{display:grid;place-items:center;min-height:300px;background:repeating-conic-gradient(#e0dfd8 0 25%,#fff 0 50%) 0 0/18px 18px}.contacts{position:absolute;right:12%;bottom:0;left:12%;display:grid;grid-template-columns:repeat(14,1fr);gap:4px;height:52px;padding:10px 12px 0;background:#090b14}.contacts i{background:var(--yellow);border:1px solid #8e7424}
	section:not(.hero){display:grid;grid-template-columns:minmax(230px,.55fr) minmax(470px,1fr);gap:clamp(2rem,8vw,7rem);padding:clamp(4rem,9vw,8rem) 0;border-top:3px solid var(--navy)}.section-copy h2{max-width:14ch;margin-top:.8rem!important;font-size:clamp(2rem,3.5vw,3rem);line-height:1.05;letter-spacing:-.035em;text-wrap:balance}.section-copy>span{display:block;max-width:40ch;margin-top:1rem;color:#575c6c}
	.frame-rom{display:grid;grid-template-columns:repeat(4,1fr) 95px;border-top:2px solid var(--navy);border-left:2px solid var(--navy)}.frame-rom figure{border-right:2px solid var(--navy);border-bottom:2px solid var(--navy)}.frame-rom figure header{display:flex;justify-content:space-between;padding:.4rem;color:#fff;background:var(--indigo);font-size:.56rem}.frame-rom figure>div{display:grid;place-items:center;aspect-ratio:1;background:#fff}.frame-rom figcaption{padding:.35rem;font-size:.56rem}.play{display:flex;flex-direction:column;align-items:center;justify-content:center;color:#fff;background:var(--navy)}.play span{font-size:1.4rem}.play b{margin-top:.5rem}.play small{color:#b7bbd1}
	.mode-table{border-top:2px solid var(--navy)}.mode-table>.head,.mode-table>div{display:grid;grid-template-columns:45px 90px 1fr 1fr;gap:1rem;padding:.85rem .4rem;border-bottom:1px solid var(--line)}.mode-table>.head{color:#737787;font-size:.62rem;font-weight:700}.mode-table kbd{display:grid;place-items:center;width:28px;height:28px;color:#fff;background:var(--indigo);border-radius:4px;font:700 .7rem/1 Archivo,sans-serif}.mode-table span,.mode-table em{font-size:.82rem}.mode-table em{color:#884a46;font-style:normal}
	.tip{grid-template-columns:130px minmax(300px,1fr) minmax(180px,.4fr)!important;align-items:center;padding:2.6rem!important;color:#fff;background:var(--navy);border:0!important}.tip b{color:#f06a64;font-size:.68rem}.tip blockquote{margin:0;font-size:1.3rem;line-height:1.35}.tip p{color:#c3c6d8;font-size:.78rem}
	.files{display:grid;grid-template-columns:repeat(2,1fr);border-top:2px solid var(--navy);border-left:2px solid var(--navy)}.files div{display:grid;grid-template-columns:90px 1fr;gap:.3rem 1rem;min-height:105px;padding:1rem;border-right:2px solid var(--navy);border-bottom:2px solid var(--navy)}.files b{grid-row:1/3;color:var(--red);font-size:1.1rem}.files span{font-weight:800}.files small{color:#666b79}
	footer{display:flex;align-items:center;gap:1.5rem;padding:3rem 0 9rem;border-top:3px solid var(--navy)}footer p{margin-right:auto!important;color:#666b79;font-size:.7rem}
	@media(max-width:850px){.hero,section:not(.hero){grid-template-columns:1fr}.hero{min-height:0}.hero>*{min-width:0}.cartridge{margin-top:1rem}.tip{grid-template-columns:1fr!important}}
	@media(max-width:620px){header nav,.brand span{display:none}.cartridge{min-height:430px;padding:4.6rem 1.2rem 4.6rem}.screen{min-height:250px}.frame-rom{grid-template-columns:repeat(4,1fr)}.play{grid-column:1/-1;min-height:75px}.mode-table>.head{display:none}.mode-table>div{grid-template-columns:38px 1fr}.mode-table span,.mode-table em{grid-column:2}.files{grid-template-columns:1fr}footer{flex-wrap:wrap}footer p{width:100%}}
</style>
