<script lang="ts">
	import { PALETTE } from '../sprites';
	import Sprite from '../Sprite.svelte';
</script>

<div class="mock riso-editor">
	<header><strong>DOODLE-DO</strong><span>RISO PROOF</span><nav><button class="active">FOCUS</button><button>GRID</button><button>LOOP</button></nav><input value="chicken-walk" aria-label="Document name"/><i>AUTOSAVED</i><button>SAVE</button><button class="export">EXPORT</button></header>
	<div class="proofs">{#each {length:4} as _,i}<button class:selected={i===1}><span>0{i+1}</span><Sprite frame={i} scale={5}/><small>{i===1?'160':'113'} ms</small></button>{/each}<button class="new">+</button></div>
	<div class="middle">
		<aside><section><h2>TOOLS</h2>{#each ['PENCIL B','ERASER E','FILL G','PICK I','SELECT M','LASSO L'] as tool,i}<button class:active={i===0}>{tool}</button>{/each}</section><section><h2>LAYERS</h2><button>HIGHLIGHTS</button><button class="active">CHICKEN</button><button>ROUGH</button></section><section><h2>PASS</h2><button class="blue">BLUE INK</button><button class="red">RED INK</button><button>BOTH</button></section></aside>
		<main><div class="canvas"><div class="red-pass"></div><Sprite frame={1} scale={24} onion={0.3} grid/></div><div class="status"><span>FRAME 02 / 04</span><b>16 × 16</b><span>1800%</span></div></main>
	</div>
	<footer><div class="palette"><b>STARTER PALETTE</b><button class="alpha" aria-label="Transparent"></button>{#each PALETTE as hex,i}<button class:selected={i===15} style="background:{hex}" aria-label={hex}></button>{/each}</div><label>BRUSH <select><option>2 PX</option></select></label><button>MIRROR</button><button>FLIP H</button><label><input type="checkbox" checked/> ONION 35%</label><button class="play">▶ 8 FPS</button></footer>
</div>

<style>
	.riso-editor{--paper:#f2eddf;--blue:#2254a3;--red:#e34435;--ink:#15223a;display:grid;grid-template-rows:auto 112px minmax(0,1fr) auto;min-height:100vh;background:var(--paper);color:var(--ink);font:12px/1.35 'IBM Plex Mono',ui-monospace,monospace}button,input,select{min-height:34px;padding:.35rem .55rem;color:var(--ink);background:var(--paper);border:2px solid var(--ink);border-radius:0;font:inherit;font-weight:800}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid var(--red);outline-offset:2px}header{display:flex;align-items:center;gap:.5rem;padding:.6rem .8rem;border-bottom:3px solid var(--ink)}header strong{font-size:1rem}header>span{font-size:.6rem}header nav{display:flex;margin-left:1rem}header nav button+button{margin-left:-2px}header .active,.export,.play{color:var(--paper);background:var(--blue)}header input{width:150px;margin-left:.5rem}header i{margin-left:auto;color:#56627a;font-size:.58rem;font-style:normal}
	.proofs{display:flex;gap:8px;padding:8px;border-bottom:3px solid var(--ink);overflow-x:auto;background:var(--blue)}.proofs>button{position:relative;display:grid;place-items:center;flex:1 0 150px;min-height:92px}.proofs button.selected{background-image:radial-gradient(var(--red) 1.1px,transparent 1.3px);background-size:7px 7px;outline:4px solid var(--red);outline-offset:-4px}.proofs span{position:absolute;top:5px;left:6px}.proofs small{position:absolute;right:6px;bottom:5px;font-size:.55rem}.proofs .new{flex:0 0 54px;font-size:1.5rem}
	.middle{display:grid;grid-template-columns:190px minmax(0,1fr);min-height:0}aside{padding:.8rem;border-right:3px solid var(--ink);overflow-y:auto}aside section+section{margin-top:1rem;padding-top:1rem;border-top:3px solid var(--ink)}h2{margin-bottom:.5rem!important;color:var(--red);font-size:.65rem}aside button{width:100%;text-align:left}aside button+button{margin-top:-2px}aside button.active{color:var(--paper);background:var(--ink)}aside .blue{color:var(--paper);background:var(--blue)}aside .red{color:var(--paper);background:var(--red)}main{display:flex;min-width:0;flex-direction:column;padding:1rem}.canvas{position:relative;display:grid;place-items:center;flex:1;min-height:430px;overflow:hidden;background-color:#f8f4e9;background-image:radial-gradient(var(--blue) 1px,transparent 1.2px);background-size:8px 8px;border:3px solid var(--ink)}.red-pass{position:absolute;width:39%;aspect-ratio:1;background-image:radial-gradient(var(--red) 1.6px,transparent 1.8px);background-size:8px 8px;opacity:.22}.canvas :global(canvas){position:relative;filter:drop-shadow(8px 5px 0 rgba(227,68,53,.35))}.status{display:flex;justify-content:space-between;padding:.55rem .75rem;color:var(--paper);background:var(--ink)}
	footer{display:flex;align-items:center;gap:.5rem;padding:.65rem .8rem;border-top:3px solid var(--ink);overflow-x:auto;white-space:nowrap}.palette{display:flex;align-items:center;gap:3px;margin-right:auto}.palette b{margin-right:.4rem;font-size:.58rem}.palette button{width:28px;min-height:28px;padding:0;border-width:1px}.palette button.selected{outline:3px solid var(--red)}.alpha{background:repeating-conic-gradient(#bbb 0 25%,#fff 0 50%) 0 0/8px 8px}footer label{display:flex;align-items:center;gap:.35rem}footer input{min-height:0}.play{min-width:90px}
	@media(max-width:720px){header>span,header input,header i,header>button:not(.export){display:none}.proofs{height:92px}.middle{grid-template-columns:1fr;grid-template-rows:auto 1fr}aside{display:flex;gap:.5rem;padding:.5rem;border-right:0;border-bottom:3px solid var(--ink);overflow-x:auto}aside section{display:flex;gap:0}aside section+section{margin:0;padding:0;border:0}aside h2,aside section:nth-child(n+2){display:none}aside button{width:auto;white-space:nowrap}main{padding:.5rem}.canvas :global(canvas){transform:scale(.72)}footer .palette b,footer>button:not(.play),footer>label:first-of-type{display:none}.palette button{width:24px;min-height:24px}}
</style>
