<script lang="ts">
	import Sprite from '../Sprite.svelte';
</script>

<div class="mock riso-page">
	<header><a href="#proof">DOODLE-DO</a><span>ANIMATION PRINT NO. 04</span><nav><a href="#frames">FRAMES</a><a href="#ship">OUTPUT</a><a class="button" href="#proof">DRAW NOW</a></nav></header>
	<main id="proof">
		<section class="poster">
			<div class="vertical">FRAME / PLAY / REPEAT</div>
			<div class="title"><p>TWO INKS. FOUR FRAMES.</p><h1>PRINT<br/>THE<br/><i>LOOP.</i></h1></div>
			<div class="disc"><div class="dots"></div><Sprite playing scale={18}/><b>8 FPS</b></div>
			<p class="intro">Draw pixel animation in the browser with playback always visible. Export a sprite sheet, atlas data, GIF, or every frame as a clean PNG.</p>
			<div class="stamp">WHITE CHICKEN<br/>WALK CYCLE<br/>DD-04</div>
		</section>
		<section class="frames" id="frames">{#each {length:4} as _,i}<figure><span>0{i+1}</span><div><Sprite frame={i} scale={9}/></div><figcaption>{i===1?'160':'113'} MS</figcaption></figure>{/each}</section>
		<section class="bottom" id="ship"><div><strong>FOCUS</strong><p>One drawing, onion skin, no distractions.</p></div><div><strong>GRID</strong><p>Every pose on one sheet.</p></div><div><strong>LOOP</strong><p>Judge the movement at speed.</p></div><div class="ship"><strong>OUTPUT</strong><p>PNG · JSON · GIF · ZIP</p><a href="#proof">OPEN THE EDITOR →</a></div></section>
	</main>
</div>

<style>
	.riso-page{--paper:#f2eddf;--blue:#2254a3;--red:#e34435;--ink:#15223a;min-height:100%;background:var(--paper);color:var(--ink);font:16px/1.4 'IBM Plex Mono',ui-monospace,monospace}a{color:inherit}header{display:flex;align-items:center;gap:2rem;padding:.85rem clamp(1rem,4vw,3.5rem);border-bottom:3px solid var(--ink)}header>a:first-child{font-weight:900;text-decoration:none}header>span{font-size:.65rem}nav{display:flex;align-items:center;gap:1.4rem;margin-left:auto}nav a{font-size:.65rem;font-weight:800;text-decoration:none}.button{padding:.55rem .8rem;color:var(--paper);background:var(--blue);border:2px solid var(--ink)}a:focus-visible{outline:3px solid var(--red);outline-offset:3px}
	main{width:min(1360px,calc(100% - 2rem));margin:auto}.poster{position:relative;display:grid;grid-template-columns:72px 1fr 1.15fr .6fr;grid-template-rows:1fr auto;min-height:650px;border-right:3px solid var(--ink);border-left:3px solid var(--ink)}.vertical{grid-row:1/3;display:flex;align-items:center;justify-content:center;padding:.75rem;color:var(--paper);background:var(--blue);font-size:.7rem;font-weight:800;letter-spacing:.12em;writing-mode:vertical-rl}.title{align-self:center;padding:2rem}.title p{font-size:.67rem;font-weight:800}.title h1{margin-top:1rem!important;font:900 clamp(4rem,8vw,8rem)/.75 Archivo,system-ui,sans-serif;letter-spacing:-.04em}.title i{color:var(--red);font-style:normal}.disc{position:relative;display:grid;place-items:center;align-self:center;aspect-ratio:1;margin:2rem;background:var(--blue);border-radius:50%;overflow:hidden}.disc .dots{position:absolute;inset:0;background-image:radial-gradient(var(--paper) 1.2px,transparent 1.4px);background-size:7px 7px;opacity:.3}.disc :global(canvas){position:relative;filter:drop-shadow(9px 9px 0 var(--red))}.disc b{position:absolute;right:12%;bottom:12%;padding:.25rem .45rem;background:var(--paper)}.intro{align-self:end;max-width:32ch;padding:2rem 1.5rem;color:#293957;font-size:.8rem}.stamp{grid-column:2/5;padding:1.2rem 2rem;color:var(--paper);background:var(--red);font-size:.72rem;font-weight:800;letter-spacing:.08em}
	.frames{display:grid;grid-template-columns:repeat(4,1fr);border:3px solid var(--ink)}figure{margin:0;border-right:3px solid var(--ink)}figure:last-child{border:0}figure>span{display:block;padding:.5rem .7rem;color:var(--paper);background:var(--blue);font-size:.65rem;font-weight:800}figure>div{display:grid;place-items:center;min-height:220px;background-image:radial-gradient(var(--blue) 1px,transparent 1.2px);background-size:8px 8px}figcaption{padding:.5rem .7rem;text-align:right;font-size:.6rem}.bottom{display:grid;grid-template-columns:repeat(4,1fr);border-right:3px solid var(--ink);border-bottom:3px solid var(--ink);border-left:3px solid var(--ink)}.bottom>div{min-height:145px;padding:1.2rem;border-right:3px solid var(--ink)}.bottom>div:last-child{border:0}.bottom strong{color:var(--red)}.bottom p{margin-top:.6rem!important;font-size:.74rem}.bottom a{display:block;margin-top:1.2rem;font-size:.68rem;font-weight:800}.ship{color:var(--paper);background:var(--blue)}.ship strong{color:var(--paper)}
	@media(max-width:780px){header>span,nav>a:not(.button){display:none}.poster{grid-template-columns:44px 1fr;grid-template-rows:auto auto auto}.vertical{grid-row:1/4}.title{padding:2rem 1.2rem}.title h1{font-size:clamp(4rem,22vw,6rem)}.disc{grid-column:2;margin:1.2rem}.disc :global(canvas){transform:scale(.72)}.intro{grid-column:2;padding:1.2rem}.stamp{grid-column:1/3}.frames{display:flex;overflow-x:auto}.frames figure{flex:0 0 78vw}.bottom{grid-template-columns:1fr 1fr}.bottom>div:nth-child(2){border-right:0}.bottom>div:nth-child(-n+2){border-bottom:3px solid var(--ink)}}
</style>
