<script lang="ts">
	import { PALETTE } from '../sprites';
	import Sprite from '../Sprite.svelte';
	const TOOLS=[['Pencil','B'],['Eraser','E'],['Fill','G'],['Pick','I'],['Select','M'],['Lasso','L'],['Wand','W'],['Polygon','P']];
</script>

<div class="mock stitch-shell"><header><strong><span>×</span> Doodle-Do</strong><div class="modes"><button class="on">Focus</button><button>Grid</button><button>Loop</button></div><label>Pattern <input value="chicken-walk"/></label><i>Saved locally</i><div class="files"><button>New</button><button>Open</button><button class="save">Save</button><button>Export</button></div></header><div class="toolbar"><div class="tools">{#each TOOLS as [name,key]}<button class:on={name==='Pencil'}>{name}<kbd>{key}</kbd></button>{/each}</div><label>Stitch <select><option>2 px</option></select></label><button>Mirror</button><button>Flip H</button><button>Flip V</button><button class="onion">Onion</button><input type="range" value="35" aria-label="Onion opacity"/><span>35%</span></div>
	<div class="middle"><main><div class="pattern"><div class="pattern-head">PATTERN DD-04 · FRAME 02</div><div class="canvas"><Sprite frame={1} scale={24} onion={0.35} grid/></div><div class="pattern-foot"><span>16 × 16</span><span>COUNTED STITCH</span><span>1-BIT ALPHA</span></div></div><div class="status"><span><i class="prev"></i>Previous</span><span><i class="next"></i>Next</span><span class="zoom">− <b>1800%</b> +</span></div></main><aside><section><div class="section-head"><h2>Loop sampler</h2><span>8 fps</span></div><div class="preview"><Sprite playing scale={7}/></div><dl><div><dt>Frames</dt><dd>4</dd></div><div><dt>Repeat</dt><dd>500 ms</dd></div></dl></section><section><div class="section-head"><h2>Fabric layers</h2><button>+</button></div><ul><li>● <span>highlights</span><button>•••</button></li><li class="active">● <span>chicken</span><button>•••</button></li><li>○ <span>rough</span><button>•••</button></li></ul><button class="wide">Merge down</button></section><section><div class="section-head"><h2>Thread card</h2><button class="locked">Locked</button></div><div class="palette"><button class="sw alpha" aria-label="Transparent"></button>{#each PALETTE as hex,i}<button class="sw" class:sel={i===15} style="background:{hex}" aria-label={hex}></button>{/each}</div></section></aside></div>
	<footer><div class="frame-head"><strong>Hoops</strong><button>New</button><button>Duplicate</button><button>Delete</button><span>Loop 01 → 04</span><label>Hold <input value="125"/> ms</label></div><ol>{#each {length:10} as _,i}<li><button class:current={i===1}>{#if i<4}<Sprite frame={i} scale={4}/>{:else}<b>+</b>{/if}</button><span>{String(i+1).padStart(2,'0')}</span></li>{/each}</ol></footer><div class="tip"><span>T06</span><p>Great pixel art usually uses surprisingly few colours. Limits make choices easier.</p><button>×</button></div></div>

<style>
	.stitch-shell{--cloth:#f3f4ef;--ink:#2b292b;--wine:#762d3b;--wine-dark:#54202b;--teal:#2d5d67;--thread:#c93f43;--gold:#d8b84b;--line:#bdc4bd;display:flex;flex-direction:column;min-height:100vh;background:#e1e4dd;color:var(--ink);font:13px/1.4 Barlow,Archivo,system-ui,sans-serif}button,input,select{min-height:29px;color:var(--ink);background:var(--cloth);border:1px solid var(--line);border-radius:4px}button{padding:.25rem .55rem}button:hover{background:#fff}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid var(--gold);outline-offset:1px}header{display:flex;align-items:center;gap:.7rem;min-height:54px;padding:.55rem .8rem;color:#fff;background:var(--wine);border-bottom:4px solid var(--wine-dark)}header strong span{display:inline-grid;place-items:center;width:20px;height:20px;color:var(--wine);background:#fff;border-radius:50%}.modes{display:flex}.modes button{color:#f1e5e8;background:transparent;border-color:#a46370;border-radius:0;margin-left:-1px}.modes button:first-child{border-radius:4px 0 0 4px}.modes button:last-child{border-radius:0 4px 4px 0}.modes .on,.save{color:#fff;background:var(--teal);border-color:#193d45}header label{display:flex;align-items:center;gap:.35rem;color:#ead9dd;font-size:.7rem}header input{width:155px;padding:.35rem}header>i{margin-left:auto;color:#e2ccd1;font-size:.66rem;font-style:normal}.files{display:flex;gap:.3rem}
	.toolbar{display:flex;align-items:center;gap:.4rem;padding:.45rem .8rem;background:var(--cloth);border-bottom:2px solid var(--wine);overflow-x:auto;white-space:nowrap}.tools{display:flex}.tools button{border-radius:0;margin-left:-1px}.tools .on,.onion{color:#fff;background:var(--teal);border-color:#193d45}kbd{margin-left:.25rem;font-size:.56rem}.toolbar label{display:flex;align-items:center;gap:.3rem;color:#666}.toolbar select{padding:.2rem}.toolbar input[type=range]{width:82px;accent-color:var(--wine)}
	.middle{display:grid;grid-template-columns:minmax(420px,1fr) 260px;flex:1;min-height:470px}.middle main{display:flex;flex-direction:column;min-width:0;padding:1rem}.pattern{display:flex;flex-direction:column;flex:1;min-height:430px;background:#fff;border:4px solid var(--wine);box-shadow:inset 0 0 0 4px #d1a06d}.pattern-head,.pattern-foot{display:flex;justify-content:space-between;padding:.55rem .8rem;color:#fff;background:var(--wine);font-size:.6rem;font-weight:700}.canvas{display:grid;place-items:center;flex:1;overflow:hidden;background-color:#fff;background-image:linear-gradient(#d8ddd7 1px,transparent 1px),linear-gradient(90deg,#d8ddd7 1px,transparent 1px);background-size:20px 20px}.status{display:flex;gap:1rem;padding:.5rem .25rem 0;color:#5f6460;font-size:.66rem}.status i{display:inline-block;width:9px;height:9px;margin-right:.3rem;border-radius:2px}.prev{background:#d04648}.next{background:#6daa2c}.zoom{margin-left:auto}.zoom b{margin:0 .5rem;color:var(--ink)}
	aside{background:var(--cloth);border-left:3px solid var(--wine)}aside section{padding:.75rem;border-bottom:3px solid var(--wine)}.section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:.55rem}.section-head h2{font-size:.8rem;color:var(--wine)}.section-head span{color:var(--teal);font-size:.62rem}.section-head button{min-height:22px;padding:.1rem .35rem}.preview{display:grid;place-items:center;aspect-ratio:1.6;background-color:#fff;background-image:linear-gradient(#d8ddd7 1px,transparent 1px),linear-gradient(90deg,#d8ddd7 1px,transparent 1px);background-size:12px 12px;border:2px solid var(--wine)}dl{margin:0}dl div{display:flex;justify-content:space-between;padding:.3rem 0;border-bottom:1px solid var(--line);font-size:.65rem}dt{color:#6b6c68}dd{margin:0;font-weight:700}aside ul{border-top:1px solid var(--line)}aside li{display:grid;grid-template-columns:auto 1fr auto;align-items:center;padding:.3rem;color:var(--teal);border-bottom:1px solid var(--line)}aside li.active{color:var(--wine);background:#eadadd}aside li button{min-height:21px;padding:.1rem .3rem;border:0;background:transparent}.wide{width:100%;margin-top:.5rem}.locked{color:#fff!important;background:var(--wine)!important}.palette{display:grid;grid-template-columns:repeat(6,1fr);gap:5px}.sw{aspect-ratio:.72;min-height:0;padding:0;border-radius:3px}.alpha{background:repeating-conic-gradient(#c5cac4 0 25%,#fff 0 50%) 0 0/8px 8px}.sw.sel{outline:3px solid var(--gold);outline-offset:1px}
	footer{background:var(--cloth);border-top:3px solid var(--wine)}.frame-head{display:flex;align-items:center;gap:.4rem;padding:.4rem .7rem;border-bottom:1px solid var(--line)}.frame-head span{margin-left:auto;color:#666}.frame-head input{width:42px;padding:.2rem;text-align:right}footer ol{display:flex;gap:.5rem;padding:.45rem .7rem!important;overflow-x:auto}footer li{flex:0 0 60px;text-align:center;color:#696a67;font-size:.58rem}footer li button{display:grid;place-items:center;width:60px;aspect-ratio:1;padding:0;background:#fff;border:4px solid #b78756;border-radius:50%}footer li button.current{outline:3px solid var(--wine);outline-offset:1px}footer li b{color:#8a8f89}
	.tip{position:fixed;right:280px;bottom:158px;display:grid;grid-template-columns:auto minmax(240px,420px) auto;align-items:center;gap:.7rem;padding:.7rem .85rem;color:#fff;background:var(--wine);border:3px double #fff}.tip span{display:grid;place-items:center;width:30px;height:30px;color:var(--wine);background:#fff;border-radius:50%;font-size:.6rem;font-weight:800}.tip p{font-size:.75rem}.tip button{color:#fff;border:0;background:transparent}
	@media(max-width:900px){.middle{grid-template-columns:1fr}aside{display:grid;grid-template-columns:repeat(3,1fr);border-left:0;border-top:3px solid var(--wine)}.tip{display:none}}
	@media(max-width:680px){header{flex-wrap:wrap}header>i,header label{display:none}.files{margin-left:auto}.files button:not(.save){display:none}.tools button:nth-child(n+5),.toolbar>button,.toolbar>label,.toolbar>input,.toolbar>span{display:none}.middle main{padding:.55rem}.canvas :global(canvas){transform:scale(.84)}aside{grid-template-columns:1fr}.frame-head button:nth-of-type(n+2),.frame-head span{display:none}}
</style>
