<script lang="ts">
	import Sprite from '../Sprite.svelte';
	const VIEWS=[['1','Focus','counting one frame','comparing the sequence'],['2','Grid','lining up every pose','single-pixel detail'],['3','Loop','reading the movement','adding new stitches']];
</script>

<div class="mock stitch-page"><header><a class="brand" href="#top"><span>×</span>Doodle-Do</a><nav><a href="#pattern">Pattern</a><a href="#views">Views</a><a href="#finish">Finish</a></nav><a class="button" href="#top">Start drawing</a></header>
	<main id="top"><section class="hero"><div class="pitch"><p>Pattern no. DD-04 · moving pixels</p><h1>Build motion one square at a time.</h1><span>Draw a frame-by-frame pixel loop in the browser. Playback stays live, practical notes appear in context, and clean files leave for your game engine.</span><div class="actions"><a class="button big" href="#pattern">Start drawing</a><a href="#finish">See the finished files →</a></div><small>No account · no upload · works offline</small></div>
		<div class="hoop"><div class="clasp"><i></i></div><div class="fabric"><Sprite playing scale={18}/></div><div class="caption"><b>WHITE CHICKEN / WALK</b><span>4 FRAMES · 8 FPS</span></div></div></section>

		<section id="pattern"><div class="section-copy"><p>Pattern row 01</p><h2>Four counted poses make one living loop.</h2><span>Because playback never stops, a weak hold or uneven step shows itself while the pattern is still under your hand.</span></div><div class="sampler">{#each {length:4} as _,i}<figure><span>{String(i+1).padStart(2,'0')}</span><div><Sprite frame={i} scale={8}/></div><figcaption>{i===1?'160':'113'} ms</figcaption></figure>{/each}<div class="thread-card"><i></i><i></i><i></i><b>8 FPS</b><small>500 ms repeat</small></div></div></section>

		<section id="views"><div class="section-copy"><p>Pattern row 02</p><h2>Change the hoop, keep the work.</h2><span>Focus, Grid, and Loop share the same document, palette, frame, zoom, and history. Each names where it snags.</span></div><div class="view-list"><div class="head"><span>Key</span><span>View</span><span>Good for</span><span>Snags on</span></div>{#each VIEWS as [key,name,great,bad]}<div><kbd>{key}</kbd><strong>{name}</strong><span>{great}</span><em>{bad}</em></div>{/each}</div></section>

		<section class="tip"><span class="knot">T06</span><blockquote>Great pixel art usually uses surprisingly few colours. Limits make choices easier.</blockquote><p>Twenty-six notes respond to relevant actions, one at a time. Dismiss any note forever.</p></section>

		<section id="finish"><div class="section-copy"><p>Pattern row 03</p><h2>Finish with files the engine can use.</h2><span>PNG sprite sheet, TexturePacker JSON, Doodle-Do project, GIF, and zipped frames. Phaser and Godot imports are verified.</span></div><div class="labels"><div><b>PNG</b><span>SPRITE SHEET</span></div><div><b>JSON</b><span>ATLAS</span></div><div><b>PROJECT</b><span>DOODLEDO</span></div><div><b>GIF / ZIP</b><span>PREVIEW / FRAMES</span></div></div></section></main>
	<footer><strong><span>×</span> Doodle-Do</strong><p>16 threads to start · 64 maximum · 1-bit alpha</p><a class="button" href="#top">Start drawing</a></footer></div>

<style>
	.stitch-page{--cloth:#f3f4ef;--ink:#2b292b;--wine:#762d3b;--wine-dark:#54202b;--teal:#2d5d67;--thread:#c93f43;--gold:#d8b84b;--line:#bdc4bd;min-height:100%;background:var(--cloth);color:var(--ink);font:16px/1.55 Barlow,Archivo,system-ui,sans-serif}a{color:inherit}header{display:flex;align-items:center;gap:2rem;padding:1rem clamp(1rem,5vw,5rem);color:#fff;background:var(--wine);border-bottom:5px solid var(--wine-dark)}.brand{display:flex;align-items:center;gap:.55rem;margin-right:auto;font-weight:800;text-decoration:none}.brand span{display:grid;place-items:center;width:24px;height:24px;color:var(--wine);background:#fff;border-radius:50%}header nav{display:flex;gap:1.5rem}header nav a{color:#ead8dd;font-size:.8rem;text-decoration:none}.button{display:inline-flex;align-items:center;justify-content:center;min-height:40px;padding:.45rem 1rem;color:#fff;background:var(--teal);border:2px solid #193d45;border-radius:4px;font-weight:800;text-decoration:none}.button:hover{background:#397480}.button:focus-visible,a:focus-visible{outline:3px solid var(--gold);outline-offset:2px}
	main,footer{width:min(1140px,calc(100% - 2rem));margin:auto}.hero{display:grid;grid-template-columns:minmax(280px,.78fr) minmax(500px,1.22fr);align-items:center;gap:clamp(3rem,8vw,8rem);min-height:720px;padding:4rem 0}.pitch>p,.section-copy>p{color:var(--wine);font-size:.68rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.pitch h1{max-width:11ch;margin-top:1rem!important;font-size:clamp(3rem,5.3vw,5.1rem);line-height:.98;letter-spacing:-.04em;text-wrap:balance}.pitch>span{display:block;max-width:41ch;margin-top:1.5rem;color:#5e5d5e;font-size:1.05rem}.actions{display:flex;align-items:center;gap:1.2rem;margin-top:1.8rem}.actions>a:last-child{color:var(--wine);font-size:.86rem;font-weight:700;text-decoration:none}.big{min-height:48px;padding:.65rem 1.2rem}.pitch small{display:block;margin-top:1.2rem;color:#6c6b6d}
	.hoop{position:relative;width:min(100%,520px);aspect-ratio:1;margin:auto;padding:38px;background:#b78756;border:10px solid #8a5a33;border-radius:50%;box-shadow:inset 0 0 0 5px #d1a06d,0 8px 14px rgba(75,49,32,.18)}.clasp{position:absolute;top:-40px;left:50%;width:72px;height:58px;transform:translateX(-50%);background:#9c6a3d;border:5px solid #704724;border-radius:6px 6px 0 0}.clasp i{display:block;width:32px;height:10px;margin:10px auto;background:#d7b07b;border:2px solid #704724}.fabric{display:grid;place-items:center;width:100%;height:100%;overflow:hidden;background-color:#fff;background-image:linear-gradient(#d8ddd7 1px,transparent 1px),linear-gradient(90deg,#d8ddd7 1px,transparent 1px);background-size:18px 18px;border-radius:50%}.caption{position:absolute;right:11%;bottom:8%;left:11%;display:flex;justify-content:space-between;padding:.55rem .7rem;color:#fff;background:var(--wine);font-size:.6rem}
	section:not(.hero){display:grid;grid-template-columns:minmax(230px,.55fr) minmax(470px,1fr);gap:clamp(2rem,8vw,7rem);padding:clamp(4rem,9vw,8rem) 0;border-top:3px double var(--wine)}.section-copy h2{max-width:14ch;margin-top:.8rem!important;font-size:clamp(2rem,3.5vw,3rem);line-height:1.05;letter-spacing:-.035em;text-wrap:balance}.section-copy>span{display:block;max-width:40ch;margin-top:1rem;color:#5d5d5d}
	.sampler{display:grid;grid-template-columns:repeat(4,1fr) 100px;gap:9px;align-items:end}.sampler figure{border:2px solid var(--wine)}.sampler figure>span{display:block;padding:.35rem;color:#fff;background:var(--wine);font-size:.62rem;font-weight:800}.sampler figure>div{display:grid;place-items:center;aspect-ratio:1;background-color:#fff;background-image:linear-gradient(#d8ddd7 1px,transparent 1px),linear-gradient(90deg,#d8ddd7 1px,transparent 1px);background-size:12px 12px}.sampler figcaption{padding:.35rem;color:#666;font-size:.62rem;text-align:right}.thread-card{display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:190px;background:var(--teal);color:#fff}.thread-card i{width:46px;height:8px;margin:3px;background:var(--thread)}.thread-card i:nth-child(2){background:var(--gold)}.thread-card i:nth-child(3){background:#fff}.thread-card b{margin-top:.7rem}.thread-card small{font-size:.58rem}
	.view-list{border-top:2px solid var(--wine)}.view-list>.head,.view-list>div{display:grid;grid-template-columns:45px 90px 1fr 1fr;gap:1rem;padding:.85rem .4rem;border-bottom:1px solid var(--line)}.view-list>.head{color:#777;font-size:.62rem;font-weight:700}.view-list kbd{display:grid;place-items:center;width:28px;height:28px;color:#fff;background:var(--wine);border-radius:50%;font:700 .7rem/1 Barlow,sans-serif}.view-list span,.view-list em{font-size:.82rem}.view-list em{color:#89505a;font-style:normal}
	.tip{grid-template-columns:70px minmax(300px,1fr) minmax(180px,.4fr)!important;align-items:center;padding:2.6rem!important;color:#fff;background:var(--wine);border:0!important}.knot{display:grid;place-items:center;width:50px;height:50px;color:var(--wine);background:#fff;border-radius:50%;font-weight:800}.tip blockquote{margin:0;font-size:1.3rem;line-height:1.35}.tip p{color:#ead9dd;font-size:.78rem}
	.labels{display:grid;grid-template-columns:repeat(2,1fr);border-top:2px solid var(--wine);border-left:2px solid var(--wine)}.labels div{display:grid;grid-template-columns:95px 1fr;align-items:center;min-height:95px;padding:1rem;border-right:2px solid var(--wine);border-bottom:2px solid var(--wine)}.labels b{color:var(--wine)}.labels span{font-size:.82rem}
	footer{display:flex;align-items:center;gap:1.5rem;padding:3rem 0 9rem;border-top:3px double var(--wine)}footer strong span{color:var(--wine)}footer p{margin-right:auto!important;color:#69686a;font-size:.72rem}
	@media(max-width:850px){.hero,section:not(.hero){grid-template-columns:1fr}.hero{min-height:0}.hero>*{min-width:0}.hoop{margin-top:4rem}.tip{grid-template-columns:60px 1fr!important}.tip p{grid-column:2}}
	@media(max-width:620px){header nav{display:none}.hoop{padding:26px}.caption{font-size:.5rem}.sampler{grid-template-columns:repeat(4,1fr)}.thread-card{grid-column:1/-1;min-height:78px}.view-list>.head{display:none}.view-list>div{grid-template-columns:38px 1fr}.view-list span,.view-list em{grid-column:2}.labels{grid-template-columns:1fr}footer{flex-wrap:wrap}footer p{width:100%}}
</style>
