<script lang="ts">
	import { PALETTE } from '../sprites';
	import Sprite from '../Sprite.svelte';
</script>

<div class="mock board-editor">
	<header><strong>Doodle-Do</strong><button>Focus</button><button class="active">Grid</button><button>Loop</button><input value="chicken-walk" aria-label="Document name"/><span>Saved locally</span><button>Save</button><button class="export">Export</button></header>
	<section class="timeline"><div class="timeline-head"><strong>STORYBOARD / 4 FRAMES</strong><button>+ New frame</button><label>Playback <select><option>8 fps</option></select></label><button>▶ Play loop</button></div><div class="cards">{#each {length:4} as _,i}<button class:selected={i===1}><span>FRAME 0{i+1}</span><Sprite frame={i} scale={8}/><small>{i===1?'160':'113'} ms</small></button>{/each}<button class="add">+</button></div></section>
	<section class="bench">
		<main><div class="canvas"><Sprite frame={1} scale={18} onion={0.3} grid/></div><div class="status"><b>FRAME 02</b><span>16 × 16</span><span>1200%</span></div></main>
		<aside><div class="toolrow">{#each ['Pencil','Erase','Fill','Pick','Select'] as tool,i}<button class:active={i===0}>{tool}</button>{/each}</div><div class="workbench"><section><h2>Layers</h2><button>Highlights <i>•••</i></button><button class="selected">Chicken <i>•••</i></button><button>Rough <i>•••</i></button></section><section><h2>Palette</h2><div class="palette"><button class="alpha" aria-label="Transparent"></button>{#each PALETTE as hex,i}<button class:selected={i===15} style="background:{hex}" aria-label={hex}></button>{/each}</div></section><section class="settings"><h2>Drawing</h2><label>Brush <select><option>2 px</option></select></label><label><input type="checkbox" checked/> Onion skin 30%</label><div><button>Mirror</button><button>Flip H</button></div></section></div></aside>
	</section>
</div>

<style>
	.board-editor{--paper:#f4f0e8;--ink:#24201d;--red:#df5a47;--blue:#315c69;display:grid;grid-template-rows:auto minmax(240px,38vh) minmax(420px,1fr);min-height:100vh;background:var(--paper);color:var(--ink);font:12px/1.35 'IBM Plex Mono',ui-monospace,monospace}button,input,select{min-height:36px;padding:.4rem .65rem;border:1px solid var(--ink);background:#fff;color:var(--ink)}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid var(--red);outline-offset:2px}header{display:flex;align-items:center;gap:.4rem;padding:.65rem 1rem;background:var(--ink);color:#fff}header strong{margin-right:.5rem;font-family:Archivo,sans-serif;font-size:1rem}header button{color:#fff;background:transparent;border-color:#766f68}header button.active{background:var(--blue)}header input{width:150px;margin-left:.5rem}header span{margin-left:auto;color:#cfc8be;font-size:.65rem}header .export{background:var(--red);border-color:#a1362b}
	.timeline{min-width:0;padding:.8rem 1rem 1rem;border-bottom:2px solid var(--ink)}.timeline-head{display:flex;align-items:center;gap:.5rem;margin-bottom:.65rem}.timeline-head strong{margin-right:auto}.timeline-head label{display:flex;align-items:center;gap:.4rem}.cards{display:flex;gap:.75rem;height:calc(100% - 46px);overflow-x:auto}.cards>button{position:relative;display:grid;place-items:center;flex:1 0 190px;min-height:170px;padding:1.8rem .5rem;background:#fff}.cards>button.selected{outline:5px solid var(--red);outline-offset:-5px}.cards span{position:absolute;top:.55rem;left:.65rem;font-size:.62rem;font-weight:800}.cards small{position:absolute;right:.65rem;bottom:.55rem}.cards .add{flex:0 0 72px;color:#6e6860;font-size:2rem}
	.bench{display:grid;grid-template-columns:minmax(420px,1.35fr) minmax(360px,.65fr);min-height:0}main{display:flex;flex-direction:column;min-width:0;padding:1rem;border-right:2px solid var(--ink)}.canvas{display:grid;place-items:center;flex:1;min-height:330px;overflow:hidden;background:repeating-conic-gradient(#e1ded7 0 25%,#fff 0 50%) 0 0/20px 20px}.status{display:flex;gap:2rem;padding:.55rem .75rem;color:#fff;background:var(--blue)}.status span:last-child{margin-left:auto}aside{display:flex;flex-direction:column;min-width:0}.toolrow{display:flex;overflow-x:auto}.toolrow button{flex:1;border-top:0;border-left:0}.toolrow .active{background:var(--red);color:#fff}.workbench{display:grid;grid-template-columns:1fr 1fr;overflow:auto}.workbench>section{padding:1rem;border-right:1px solid #aaa39b;border-bottom:1px solid #aaa39b}.workbench h2{margin-bottom:.7rem!important;font-family:Archivo,sans-serif;font-size:.82rem}.workbench section>button{display:flex;justify-content:space-between;width:100%;border-width:1px 0 0}.workbench section>button:last-child{border-bottom-width:1px}.workbench section>button.selected{background:#efd5d0}.palette{display:grid;grid-template-columns:repeat(4,1fr);gap:4px}.palette button{aspect-ratio:1;min-height:28px;padding:0}.palette button.selected{outline:3px solid var(--red)}.alpha{background:repeating-conic-gradient(#aaa 0 25%,#fff 0 50%) 0 0/8px 8px}.settings{grid-column:1/-1}.settings label{display:flex;align-items:center;gap:.5rem;margin-bottom:.6rem}.settings input{min-height:0}.settings div{display:flex;gap:.4rem}
	@media(max-width:760px){.board-editor{grid-template-rows:auto 200px auto}.board-editor header input,.board-editor header span,.board-editor header button:not(.active):not(.export){display:none}.timeline-head label,.timeline-head button:not(:last-child){display:none}.cards>button{flex-basis:142px;min-height:125px}.cards :global(canvas){transform:scale(.75)}.bench{grid-template-columns:1fr}.bench main{min-height:430px;border-right:0;border-bottom:2px solid var(--ink)}.canvas :global(canvas){transform:scale(.82)}.workbench{grid-template-columns:1fr 1fr}}
</style>
