<script lang="ts">
	import { PALETTE } from '../sprites';
	import Sprite from '../Sprite.svelte';
	const TOOLS=[['Pencil','B'],['Eraser','E'],['Fill','G'],['Pick','I'],['Select','M'],['Lasso','L'],['Wand','W'],['Polygon','P']];
</script>

<div class="mock carton-shell">
	<header><span class="stamp">DD</span><strong>Doodle-Do</strong><div class="modes"><button class="on">Focus</button><button>Grid</button><button>Loop</button></div><input value="chicken-walk" aria-label="Document name"/><span class="saved">Packed locally</span><div class="files"><button>New</button><button>Open</button><button class="save">Save</button><button>Export</button></div></header>
	<div class="toolbar"><div class="tools">{#each TOOLS as [name,key]}<button class:on={name==='Pencil'}>{name}<kbd>{key}</kbd></button>{/each}</div><label>Brush <select><option>2 px</option></select></label><button>Mirror</button><button>Flip H</button><button>Flip V</button><button class="onion">Onion</button><input type="range" value="35" aria-label="Onion opacity"/><span>35%</span></div>
	<div class="work">
		<main><div class="screen"><Sprite frame={1} scale={24} onion={0.35} grid/></div><div class="status"><span>Cell 02 of 12</span><span>16 × 16</span><span><i class="prev"></i>Previous</span><span><i class="next"></i>Next</span><span class="zoom">− <b>1800%</b> +</span></div></main>
		<aside>
			<section><div class="section-head"><h2>Loop check</h2><span>8 fps</span></div><div class="preview"><Sprite playing scale={7}/></div><div class="facts"><span>4 filled</span><span>500 ms</span><button>Pause</button></div></section>
			<section><div class="section-head"><h2>Layers</h2><button>+</button></div><ul><li><button>●</button><span>highlights</span><button>•••</button></li><li class="active"><button>●</button><span>chicken</span><button>•••</button></li><li><button>○</button><span>rough</span><button>•••</button></li></ul><button class="wide">Merge down</button></section>
			<section><div class="section-head"><h2>Palette <small>16 / 64</small></h2><button class="locked">Locked</button></div><div class="palette"><button class="sw alpha" aria-label="Transparent"></button>{#each PALETTE as hex,i}<button class="sw" class:sel={i===15} style="background:{hex}" aria-label={hex}></button>{/each}</div></section>
		</aside>
	</div>
	<footer><div class="frame-head"><strong>Carton</strong><button>New frame</button><button>Duplicate</button><button>Delete</button><span>Loop 01 → 04</span><label>Hold <input value="125"/> ms</label></div><ol>{#each {length:12} as _,i}<li><span>{String(i+1).padStart(2,'0')}</span><button class:filled={i<4} class:current={i===1}>{#if i<4}<Sprite frame={i} scale={4}/>{:else}<b>+</b>{/if}</button></li>{/each}</ol></footer>
	<div class="tip"><span>T10</span><p>A tight four-frame loop often reads better than a loose eight. The loop preview never lies.</p><button>×</button></div>
</div>

<style>
	.carton-shell{--pulp:#c8c4b7;--pulp2:#b2aea1;--shell:#f4f1e8;--ink:#292923;--muted:#66665d;--line:#999588;--red:#a93229;--yellow:#e2b43b;display:flex;flex-direction:column;min-height:100vh;background:var(--pulp);color:var(--ink);font:13px/1.4 Barlow,Archivo,system-ui,sans-serif}button,input,select{min-height:29px;color:var(--ink);background:var(--shell);border:1px solid var(--line);border-radius:4px}button{padding:.25rem .55rem}button:hover{background:#fffdf7}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid var(--yellow);outline-offset:1px}
	header{display:flex;align-items:center;gap:.7rem;min-height:54px;padding:.55rem .8rem;background:var(--shell);border-bottom:2px solid var(--ink)}.stamp{display:grid;place-items:center;width:28px;height:28px;color:var(--shell);background:var(--red);border-radius:50%;font-size:.6rem;font-weight:800}.modes{display:flex}.modes button{border-radius:0;margin-left:-1px}.modes button:first-child{border-radius:4px 0 0 4px}.modes button:last-child{border-radius:0 4px 4px 0}.modes .on,.save{color:var(--shell);background:var(--red);border-color:var(--red)}header>input{width:170px;padding:.35rem}.saved{margin-left:auto;color:var(--muted);font-size:.68rem}.files{display:flex;gap:.3rem}
	.toolbar{display:flex;align-items:center;gap:.4rem;padding:.45rem .8rem;background:#b7b3a6;border-bottom:1px solid var(--line);overflow-x:auto;white-space:nowrap}.tools{display:flex}.tools button{border-radius:0;margin-left:-1px}.tools button:first-child{border-radius:4px 0 0 4px}.tools button:last-child{border-radius:0 4px 4px 0}.tools .on,.onion{color:var(--shell);background:var(--red);border-color:var(--red)}kbd{margin-left:.25rem;font-size:.58rem}.toolbar label{display:flex;align-items:center;gap:.3rem;color:#55554e}.toolbar select{padding:.2rem}.toolbar input[type=range]{width:82px;accent-color:var(--red)}
	.work{display:grid;grid-template-columns:minmax(420px,1fr) 260px;flex:1;min-height:470px}.work main{display:flex;flex-direction:column;min-width:0;padding:1rem}.screen{display:grid;place-items:center;flex:1;min-height:420px;background:repeating-conic-gradient(#ece9df 0 25%,#fffdf7 0 50%) 0 0/20px 20px;border:2px solid var(--ink);border-radius:9px;box-shadow:inset 0 0 0 7px var(--pulp2)}.status{display:flex;gap:1rem;padding:.5rem .2rem 0;color:#55554e;font-size:.68rem}.status i{display:inline-block;width:9px;height:9px;margin-right:.3rem;border-radius:2px}.prev{background:#d04648}.next{background:#6daa2c}.zoom{margin-left:auto}.zoom b{color:var(--ink);margin:0 .5rem}
	aside{background:var(--shell);border-left:2px solid var(--ink)}aside section{padding:.75rem;border-bottom:2px solid var(--ink)}.section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:.55rem}.section-head h2{font-size:.8rem}.section-head small,.section-head>span{color:var(--muted);font-size:.63rem}.section-head button{min-height:24px;padding:.1rem .4rem}.preview{display:grid;place-items:center;aspect-ratio:1.6;background:repeating-conic-gradient(#e8e5dc 0 25%,#fffdf7 0 50%) 0 0/12px 12px;border:1px solid var(--line);border-radius:50%}.facts{display:flex;align-items:center;gap:.7rem;margin-top:.5rem;color:var(--muted);font-size:.65rem}.facts button{margin-left:auto}aside ul{border-top:1px solid var(--line)}aside li{display:grid;grid-template-columns:auto 1fr auto;align-items:center;padding:.3rem;border-bottom:1px solid var(--line)}aside li.active{background:#ead2cb}aside li button{min-height:22px;padding:.1rem .3rem;border:0;background:transparent}.wide{width:100%;margin-top:.5rem}.locked{color:var(--red)!important}.palette{display:grid;grid-template-columns:repeat(6,1fr);gap:5px}.sw{aspect-ratio:1;min-height:0;padding:0;border-radius:50%}.alpha{background:repeating-conic-gradient(#bbb7ac 0 25%,#fff 0 50%) 0 0/8px 8px}.sw.sel{outline:3px solid var(--red);outline-offset:1px}
	footer{background:#b6b2a5;border-top:2px solid var(--ink)}.frame-head{display:flex;align-items:center;gap:.4rem;padding:.4rem .7rem}.frame-head span{margin-left:auto}.frame-head label{color:#55554e}.frame-head input{width:44px;padding:.2rem;text-align:right}footer ol{display:flex;gap:.55rem;padding:.5rem .7rem!important;overflow-x:auto}footer li{flex:0 0 58px;text-align:center;color:#5c5b53;font-size:.58rem}footer li>button{display:grid;place-items:center;width:58px;aspect-ratio:.86;padding:0;background:#9e9a8e;border:0;border-radius:50%;box-shadow:inset 0 4px 6px rgba(58,56,49,.25)}footer li>button.filled{background:var(--shell)}footer li>button.current{outline:3px solid var(--red);outline-offset:2px}footer li b{font-size:1rem;color:#77746a}
	.tip{position:fixed;right:280px;bottom:156px;display:grid;grid-template-columns:auto minmax(240px,430px) auto;align-items:center;gap:.7rem;padding:.7rem .85rem;background:var(--shell);border:2px solid var(--ink);transform:rotate(-.5deg)}.tip span{display:grid;place-items:center;width:30px;height:30px;color:var(--shell);background:var(--red);border-radius:50%;font-size:.6rem;font-weight:800}.tip p{font-size:.75rem}.tip button{border:0;background:transparent}
	@media(max-width:900px){.work{grid-template-columns:1fr}aside{display:grid;grid-template-columns:repeat(3,1fr);border-left:0;border-top:2px solid var(--ink)}.tip{display:none}}
	@media(max-width:680px){header{flex-wrap:wrap}.saved,header>input{display:none}.files{margin-left:auto}.files button:not(.save){display:none}.tools button:nth-child(n+5),.toolbar>button,.toolbar>label,.toolbar>input,.toolbar>span{display:none}.work main{padding:.55rem}.screen{min-height:55vh}aside{grid-template-columns:1fr}.status span:nth-child(3),.status span:nth-child(4){display:none}.frame-head button:nth-of-type(n+2),.frame-head span{display:none}}
</style>
