<script lang="ts">
	import { PALETTE } from '../sprites';
	import Sprite from '../Sprite.svelte';
</script>

<div class="mock xerox-editor">
	<header><strong>DOODLE-DO</strong><button class="active">FOCUS</button><button>GRID</button><button>LOOP</button><input value="chicken-walk" aria-label="Document name"/><span>SAVED LOCALLY</span><button>SAVE</button><button class="export">EXPORT</button></header>
	<main>
		<div class="sheet"><div class="label">FRAME 02 / 04</div><Sprite frame={1} scale={24} onion={0.3} grid/><div class="sheet-foot"><b>16 × 16</b><span>1800%</span></div></div>
		<section class="window tools"><h2>TOOLS <span>×</span></h2>{#each ['PENCIL B','ERASER E','FILL G','PICK I','SELECT M','LASSO L'] as tool,i}<button class:active={i===0}>{tool}</button>{/each}<label>SIZE <select><option>2 PX</option></select></label><button>MIRROR</button><button>FLIP H</button></section>
		<section class="window frames"><h2>FRAMES <span>×</span></h2><div>{#each {length:4} as _,i}<button class:selected={i===1}><Sprite frame={i} scale={5}/><small>0{i+1}</small></button>{/each}<button class="add">+</button></div><label>PLAYBACK <select><option>8 FPS</option></select></label><button>▶ PLAY</button></section>
		<section class="window layers"><h2>LAYERS <span>×</span></h2><button>HIGHLIGHTS <i>•••</i></button><button class="active">CHICKEN <i>•••</i></button><button>ROUGH <i>•••</i></button></section>
		<section class="window palette"><h2>PALETTE <span>×</span></h2><div><button class="alpha" aria-label="Transparent"></button>{#each PALETTE as hex,i}<button class:selected={i===15} style="background:{hex}" aria-label={hex}></button>{/each}</div></section>
		<div class="tip">THE RED GHOST IS THE PREVIOUS FRAME. DRAW WHERE THE PIXELS MOVED TO.<button>×</button></div>
	</main>
</div>

<style>
	.xerox-editor{--paper:#eeeeea;--ink:#111;--red:#d93b35;display:grid;grid-template-rows:auto minmax(0,1fr);min-height:100vh;background-color:#c9c9c5;background-image:radial-gradient(#777 .8px,transparent 1px);background-size:7px 7px;color:var(--ink);font:12px/1.35 'IBM Plex Mono',ui-monospace,monospace}button,input,select{min-height:34px;padding:.35rem .55rem;color:var(--ink);background:var(--paper);border:2px solid var(--ink);border-radius:0;font:inherit;font-weight:800}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid var(--red);outline-offset:2px}header{position:relative;z-index:3;display:flex;align-items:center;gap:.45rem;padding:.6rem .8rem;background:var(--ink);color:var(--paper)}header strong{margin-right:.5rem;font-size:1rem}header button{color:var(--paper);background:var(--ink);border-color:#777}header .active,header .export{background:var(--red);border-color:var(--paper)}header input{width:150px;margin-left:.5rem}header span{margin-left:auto;font-size:.58rem}
	main{position:relative;min-height:720px;overflow:hidden}.sheet{position:absolute;inset:5% 21% 7% 17%;display:grid;place-items:center;background-color:#fff;background-image:repeating-conic-gradient(#deded9 0 25%,#fff 0 50%);background-size:22px 22px;border:4px solid var(--ink);box-shadow:12px 12px 0 rgba(0,0,0,.35);transform:rotate(-.5deg)}.label{position:absolute;top:0;left:0;padding:.5rem .7rem;background:var(--ink);color:#fff;font-weight:900}.sheet-foot{position:absolute;right:0;bottom:0;left:0;display:flex;justify-content:space-between;padding:.5rem .7rem;background:var(--ink);color:#fff}
	.window{position:absolute;background:var(--paper);border:3px solid var(--ink);box-shadow:7px 7px 0 var(--ink)}.window h2{display:flex;justify-content:space-between;margin:0 0 .6rem!important;padding:.45rem .6rem;background:var(--ink);color:#fff;font-size:.65rem}.tools{top:4%;left:1.5%;width:178px;padding-bottom:.7rem;transform:rotate(-1deg)}.tools>button,.layers>button{display:flex;justify-content:space-between;width:calc(100% - 1rem);margin:0 .5rem -2px}.tools>button.active,.layers>button.active{background:var(--red);color:#fff}.tools label{display:flex;align-items:center;gap:.4rem;margin:.7rem .5rem 0}.frames{right:1.5%;bottom:4%;width:280px;padding-bottom:.7rem;transform:rotate(1deg)}.frames>div{display:flex;gap:4px;padding:0 .6rem;overflow-x:auto}.frames>div button{position:relative;display:grid;place-items:center;flex:0 0 56px;padding:0;aspect-ratio:1}.frames button.selected{outline:3px solid var(--red)}.frames small{position:absolute;top:2px;left:3px;font-size:.5rem}.frames label{display:inline-flex;align-items:center;gap:.35rem;margin:.7rem .4rem 0 .6rem}.layers{top:5%;right:2%;width:190px;padding-bottom:.7rem;transform:rotate(1deg)}.layers i{font-style:normal}.palette{right:3%;top:38%;width:180px;padding-bottom:.7rem;transform:rotate(-1deg)}.palette>div{display:grid;grid-template-columns:repeat(4,1fr);gap:3px;padding:0 .6rem}.palette button{aspect-ratio:1;min-height:0;padding:0}.palette button.selected{outline:3px solid var(--red)}.alpha{background:repeating-conic-gradient(#aaa 0 25%,#fff 0 50%) 0 0/8px 8px}.tip{position:absolute;left:20%;bottom:3%;max-width:420px;padding:.8rem 2.4rem .8rem .9rem;background:#fff;border:3px solid var(--ink);box-shadow:6px 6px 0 var(--red);font-weight:800;transform:rotate(-1deg)}.tip button{position:absolute;top:4px;right:4px;min-height:24px;padding:.1rem .35rem;border-width:1px}
	@media(max-width:760px){header input,header span,header>button:not(.export){display:none}main{min-height:760px}.sheet{inset:118px 1rem 180px}.sheet :global(canvas){transform:scale(.72)}.tools{top:10px;left:10px;right:10px;width:auto;display:flex;gap:0;padding:0;overflow-x:auto;transform:none}.tools h2,.tools label,.tools button:nth-of-type(n+5){display:none}.tools>button{width:auto;margin:0 -2px 0 0;white-space:nowrap}.layers{top:auto;right:auto;bottom:110px;left:12px;width:150px}.layers>button:not(.active){display:none}.palette{top:auto;right:12px;bottom:100px;width:150px}.palette>div{grid-template-columns:repeat(4,1fr)}.frames{right:10px;bottom:8px;left:10px;width:auto;transform:none}.frames>label,.frames>button{display:none}.tip{display:none}}
</style>
