<script lang="ts">
	import Sprite from '../Sprite.svelte';
</script>

<div class="mock xerox-page">
	<header><a href="#zine">DOODLE-DO</a><span>ISSUE 001 · FOUR FRAMES FOREVER</span><a class="open" href="#zine">OPEN EDITOR</a></header>
	<main id="zine">
		<section class="cover"><div class="tape one"></div><div class="tape two"></div><h1>MAKE<br/>IT<br/>MOVE!</h1><div class="chicken"><Sprite playing scale={19}/><b>WHITE CHICKEN<br/>WALK TEST</b></div><p class="dek">A tiny pixel-animation studio that works offline, plays while you draw, and exports files your engine already understands.</p><a class="start" href="#zine">START DRAWING →</a><span class="stamp">NO CLOUD<br/>NO ACCOUNT<br/>NO NONSENSE</span></section>
		<section class="strip"><h2>THE EVIDENCE</h2><div>{#each {length:4} as _,i}<figure><span>0{i+1}</span><Sprite frame={i} scale={8}/><figcaption>{i===1?'160':'113'} MS</figcaption></figure>{/each}</div></section>
		<section class="clippings"><article><h2>FOCUS</h2><p>Fix one drawing with the neighboring poses ghosted behind it.</p></article><article><h2>GRID</h2><p>Pin every frame to the wall and catch the silhouette that breaks.</p></article><article><h2>LOOP</h2><p>Stop drawing. Watch the timing. Believe what the movement tells you.</p></article><article class="red"><h2>SHIP IT</h2><p>PNG sprite sheet · TexturePacker JSON · GIF · zipped frames.</p><a href="#zine">MAKE A LOOP →</a></article></section>
	</main>
</div>

<style>
	.xerox-page{--paper:#eeeeea;--ink:#111;--red:#d93b35;min-height:100%;padding-bottom:4rem;background-color:var(--paper);background-image:radial-gradient(#b8b8b3 .7px,transparent .9px);background-size:5px 5px;color:var(--ink);font:16px/1.35 'IBM Plex Mono',ui-monospace,monospace}a{color:inherit}header{display:flex;align-items:center;gap:2rem;padding:.9rem clamp(1rem,4vw,3rem);background:var(--ink);color:var(--paper)}header>a:first-child{font-weight:900;text-decoration:none}header span{font-size:.62rem}.open{margin-left:auto;padding:.55rem .8rem;background:var(--red);border:2px solid var(--paper);font-weight:800;text-decoration:none}a:focus-visible{outline:3px solid var(--red);outline-offset:3px}
	main{width:min(1220px,calc(100% - 2rem));margin:auto}.cover{position:relative;min-height:650px;margin:2rem 0;padding:clamp(2rem,5vw,5rem);overflow:hidden;background:var(--paper);border:4px solid var(--ink);box-shadow:12px 12px 0 var(--ink)}.cover h1{position:relative;z-index:1;font:950 clamp(5rem,13vw,11rem)/.68 Archivo,system-ui,sans-serif;letter-spacing:-.04em;transform:rotate(-2deg)}.cover h1::after{content:'MAKE IT MOVE!';position:absolute;top:8px;left:8px;z-index:-1;color:transparent;-webkit-text-stroke:2px var(--red)}.chicken{position:absolute;right:8%;bottom:9%;display:grid;place-items:center;width:min(42vw,480px);aspect-ratio:1;background:#fff;border:4px solid var(--ink);transform:rotate(3deg);box-shadow:10px 10px 0 var(--red)}.chicken b{position:absolute;right:.8rem;bottom:.7rem;padding:.4rem;background:var(--ink);color:#fff;font-size:.6rem}.dek{position:absolute;right:7%;top:9%;width:30ch;padding:1rem;background:#fff;border:3px solid var(--ink);font-weight:700;transform:rotate(2deg)}.start{position:absolute;left:8%;bottom:10%;padding:.8rem 1rem;background:var(--ink);color:#fff;font-weight:900;text-decoration:none;transform:rotate(-2deg)}.stamp{position:absolute;right:42%;bottom:9%;padding:.7rem;color:var(--red);border:4px solid var(--red);font-size:.7rem;font-weight:900;transform:rotate(8deg)}.tape{position:absolute;width:160px;height:34px;background:rgba(217,59,53,.78)}.tape.one{top:22px;left:38%;transform:rotate(-8deg)}.tape.two{right:18%;bottom:24px;transform:rotate(6deg)}
	.strip{margin-top:4rem}.strip h2{display:inline-block;padding:.35rem .6rem;background:var(--ink);color:#fff;font-size:1rem;transform:rotate(-1deg)}.strip>div{display:flex;margin-top:1rem;overflow-x:auto}.strip figure{position:relative;display:grid;place-items:center;flex:1 0 240px;min-height:250px;margin:0;background:#fff;border:3px solid var(--ink)}.strip figure+figure{margin-left:-3px}.strip figure:nth-child(even){transform:translateY(8px)}.strip figure>span{position:absolute;top:.5rem;left:.6rem;font-weight:900}.strip figcaption{position:absolute;right:.6rem;bottom:.5rem;font-size:.6rem}.clippings{display:grid;grid-template-columns:1fr 1fr 1fr 1.2fr;align-items:start;gap:1.5rem;margin-top:4rem}.clippings article{min-height:180px;padding:1.2rem;background:#fff;border:3px solid var(--ink);box-shadow:7px 7px 0 var(--ink);transform:rotate(-1deg)}.clippings article:nth-child(2){transform:rotate(2deg) translateY(18px)}.clippings article:nth-child(3){transform:rotate(-2deg) translateY(-10px)}.clippings h2{font-family:Archivo,sans-serif;font-size:2rem}.clippings p{margin-top:.8rem!important;font-size:.78rem}.clippings .red{background:var(--red);color:#fff;transform:rotate(1deg)}.clippings a{display:block;margin-top:1.5rem;font-weight:900}
	@media(max-width:760px){header span{display:none}.cover{min-height:760px;padding:2rem 1.2rem}.cover h1{font-size:clamp(4.5rem,24vw,7rem)}.dek{top:300px;right:1.2rem;left:1.2rem;width:auto}.chicken{right:1.2rem;bottom:95px;width:82%}.chicken :global(canvas){transform:scale(.72)}.start{left:1.2rem;bottom:24px}.stamp{display:none}.clippings{grid-template-columns:1fr}.clippings article:nth-child(n){transform:none}.strip figure{flex-basis:76vw}}
</style>
