<script lang="ts">
	import { PALETTE } from '../sprites';
	import Sprite from '../Sprite.svelte';
	const TOOLS=[['Pencil','B'],['Eraser','E'],['Fill','G'],['Pick','I'],['Select','M'],['Lasso','L'],['Wand','W'],['Polygon','P']];
</script>

<div class="mock plan-shell">
	<header><strong>DOODLE-DO</strong><span>DD-01 / COOP PLAN</span><div class="modes"><button class="on">FOCUS 1</button><button>GRID 2</button><button>LOOP 3</button></div><label>FILE <input value="chicken-walk"/></label><i>SAVED LOCAL</i><div class="files"><button>NEW</button><button>OPEN</button><button class="save">SAVE</button><button>EXPORT</button></div></header>
	<div class="toolbar"><div class="tools">{#each TOOLS as [name,key]}<button class:on={name==='Pencil'}>{name.toUpperCase()} <kbd>{key}</kbd></button>{/each}</div><label>BRUSH <select><option>2 PX</option></select></label><button>MIRROR</button><button>FLIP H</button><button>FLIP V</button><button class="onion">ONION</button><input type="range" value="35" aria-label="Onion opacity"/><span>35%</span></div>
	<div class="middle"><main><div class="sheet"><div class="sheet-title">FRAME BAY F-02 / 16 × 16 / REV B</div><div class="canvas"><Sprite frame={1} scale={24} onion={0.35} grid/></div><div class="dimension"><span>0</span><i></i><span>16 PX</span></div></div><div class="status"><span><i class="prev"></i>PREVIOUS</span><span><i class="next"></i>NEXT</span><span>ALPHA 1 BIT</span><span class="zoom">− <b>1800%</b> +</span></div></main><aside><section><div class="section-head"><h2>LOOP ELEVATION</h2><span>08 FPS</span></div><div class="preview"><Sprite playing scale={7}/></div><dl><div><dt>FRAMES</dt><dd>04</dd></div><div><dt>CYCLE</dt><dd>500 MS</dd></div><div><dt>RANGE</dt><dd>01 → 04</dd></div></dl></section><section><div class="section-head"><h2>LAYER SCHEDULE</h2><button>+</button></div><ul><li>● <span>HIGHLIGHTS</span><button>•••</button></li><li class="active">● <span>CHICKEN</span><button>•••</button></li><li>○ <span>ROUGH</span><button>•••</button></li></ul><button class="wide">MERGE DOWN</button></section><section><div class="section-head"><h2>COLOUR KEY</h2><button class="locked">LOCKED</button></div><div class="palette"><button class="sw alpha" aria-label="Transparent"></button>{#each PALETTE as hex,i}<button class="sw" class:sel={i===15} style="background:{hex}" aria-label={hex}></button>{/each}</div></section></aside></div>
	<footer><div class="frame-head"><strong>FRAME BAYS</strong><button>NEW</button><button>DUPLICATE</button><button>DELETE</button><span>LOOP 01 → 04</span><label>HOLD <input value="125"/> MS</label></div><ol>{#each {length:10} as _,i}<li><span>F-{String(i+1).padStart(2,'0')}</span><button class:current={i===1}>{#if i<4}<Sprite frame={i} scale={4}/>{:else}<b>+</b>{/if}</button></li>{/each}</ol></footer>
	<div class="revision"><b>REV T02</b><p>THE RED GHOST IS YOUR PREVIOUS FRAME. DRAW WHERE THINGS MOVED TO, NOT WHERE THEY WERE.</p><button>×</button></div>
</div>

<style>
	.plan-shell{--blue:#124b69;--blue2:#0b3b55;--line:#b8d4df;--white:#f3f7f6;--red:#d9483e;--yellow:#e7ce58;display:flex;flex-direction:column;min-height:100vh;background:var(--blue);color:var(--white);font:12px/1.4 'Martian Mono',monospace}button,input,select{min-height:29px;color:var(--white);background:var(--blue);border:1px solid var(--line);border-radius:0}button{padding:.25rem .5rem}button:hover{background:#1d6286}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid var(--yellow);outline-offset:1px}
	header{display:flex;align-items:center;gap:.65rem;min-height:54px;padding:.55rem .75rem;background:var(--blue2);border-bottom:1px solid var(--line)}header>span{color:#a9c7d3;font-size:.55rem}.modes{display:flex}.modes button{margin-left:-1px}.modes .on,.save{color:#fff;background:var(--red);border-color:var(--red)}header label{display:flex;align-items:center;gap:.35rem;color:#b8d0d9;font-size:.55rem}header input{width:155px;padding:.35rem;background:var(--white);color:#14384a}header>i{margin-left:auto;color:#acd0be;font-size:.54rem;font-style:normal}.files{display:flex;gap:.3rem}
	.toolbar{display:flex;align-items:center;gap:.35rem;padding:.45rem .75rem;background:var(--blue);border-bottom:1px solid var(--line);overflow-x:auto;white-space:nowrap}.tools{display:flex}.tools button{margin-left:-1px}.tools .on,.onion{background:var(--white);color:var(--blue2)}kbd{font-size:.52rem}.toolbar label{display:flex;align-items:center;gap:.3rem;color:#b8d0d9;font-size:.55rem}.toolbar select{padding:.2rem}.toolbar input[type=range]{width:80px;accent-color:var(--red)}
	.middle{display:grid;grid-template-columns:minmax(420px,1fr) 260px;flex:1;min-height:470px;background-color:var(--blue);background-image:linear-gradient(rgba(243,247,246,.06) 1px,transparent 1px),linear-gradient(90deg,rgba(243,247,246,.06) 1px,transparent 1px);background-size:32px 32px}.middle main{display:flex;flex-direction:column;min-width:0;padding:1rem}.sheet{display:flex;flex-direction:column;width:min(72vh,650px);max-width:calc(100% - 2rem);aspect-ratio:1;margin:auto;border:2px solid var(--white);background:rgba(8,52,75,.72)}.sheet-title{padding:.55rem .7rem;border-bottom:1px solid var(--line);font-size:.58rem}.canvas{display:grid;place-items:center;flex:1;overflow:hidden}.dimension{display:flex;align-items:center;gap:.5rem;padding:.45rem .7rem;border-top:1px solid var(--line);font-size:.52rem}.dimension i{display:block;width:90px;height:7px;border:1px solid var(--white);border-top:0}.status{display:flex;gap:1rem;padding:.5rem .25rem 0;color:#c1d7df;font-size:.54rem}.status i{display:inline-block;width:9px;height:9px;margin-right:.3rem}.prev{background:#d04648}.next{background:#6daa2c}.zoom{margin-left:auto}.zoom b{color:#fff;margin:0 .5rem}
	aside{background:var(--blue2);border-left:1px solid var(--line)}aside section{padding:.7rem;border-bottom:1px solid var(--line)}.section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:.5rem}.section-head h2{font-size:.6rem}.section-head span{color:var(--red);font-size:.55rem}.section-head button{min-height:22px;padding:.1rem .3rem}.preview{display:grid;place-items:center;aspect-ratio:1.6;border:1px solid var(--line)}dl{margin:0}dl div{display:flex;justify-content:space-between;padding:.3rem 0;border-bottom:1px solid rgba(184,212,223,.5);font-size:.54rem}dt{color:#a9c7d3}dd{margin:0}aside ul{border-top:1px solid var(--line)}aside li{display:grid;grid-template-columns:auto 1fr auto;align-items:center;padding:.3rem;border-bottom:1px solid rgba(184,212,223,.5);color:#b9d1da;font-size:.56rem}aside li.active{color:#fff;background:#1c6082}aside li button{min-height:21px;padding:.1rem .3rem;border:0;background:transparent}.wide{width:100%;margin-top:.5rem}.locked{color:#fff!important;background:var(--red)!important}.palette{display:grid;grid-template-columns:repeat(6,1fr);gap:4px}.sw{aspect-ratio:1;min-height:0;padding:0}.alpha{background:repeating-conic-gradient(#5d8293 0 25%,#dbe7e8 0 50%) 0 0/8px 8px}.sw.sel{outline:2px solid var(--red);outline-offset:1px}
	footer{background:var(--blue2);border-top:1px solid var(--line)}.frame-head{display:flex;align-items:center;gap:.4rem;padding:.4rem .7rem;border-bottom:1px solid rgba(184,212,223,.5);font-size:.54rem}.frame-head span{margin-left:auto}.frame-head label{color:#bad1da}.frame-head input{width:42px;padding:.2rem;text-align:right;background:var(--white);color:var(--blue2)}footer ol{display:flex;gap:.4rem;padding:.45rem .7rem!important;overflow-x:auto}footer li{flex:0 0 58px;text-align:center;color:#b8d0d9;font-size:.5rem}footer li button{display:grid;place-items:center;width:58px;aspect-ratio:1;padding:0;background:var(--blue);border:1px solid var(--line)}footer li button.current{outline:2px solid var(--red);outline-offset:1px}footer li b{color:#7fa4b4}
	.revision{position:fixed;right:280px;bottom:154px;display:grid;grid-template-columns:auto minmax(260px,440px) auto;align-items:center;gap:.7rem;padding:.65rem .8rem;color:#12384b;background:var(--white);border:2px solid var(--red)}.revision b{color:#b9362f;font-size:.56rem}.revision p{font-size:.56rem}.revision button{color:#12384b;border:0;background:transparent}
	@media(max-width:900px){.middle{grid-template-columns:1fr}aside{display:grid;grid-template-columns:repeat(3,1fr);border-left:0;border-top:1px solid var(--line)}.revision{display:none}}
	@media(max-width:680px){header{flex-wrap:wrap}header>span,header>i,header label{display:none}.files{margin-left:auto}.files button:not(.save){display:none}.tools button:nth-child(n+5),.toolbar>button,.toolbar>label,.toolbar>input,.toolbar>span{display:none}.middle main{padding:.55rem}.sheet{max-width:100%}.canvas :global(canvas){transform:scale(.84)}aside{grid-template-columns:1fr}.frame-head button:nth-of-type(n+2),.frame-head span{display:none}.status span:nth-child(3){display:none}}
</style>
