<script lang="ts">
	import Sprite from '../Sprite.svelte';
	const VIEWS=[['01','FOCUS','single-frame construction','sequence comparison'],['02','GRID','pose-to-pose alignment','pixel-detail work'],['03','LOOP','timing inspection','drawing operations']];
</script>

<div class="mock plan-page">
	<header><a href="#top" class="mark">DOODLE-DO <span>COOP PLAN / ANIMATION WORKS</span></a><nav><a href="#frames">Frame bays</a><a href="#views">Views</a><a href="#out">Build sheet</a></nav><a class="action" href="#top">Open editor</a></header>
	<main id="top">
		<section class="hero"><div class="pitch"><p>Drawing DD-01 · scale 16:1</p><h1>Plan the poses.<br/>Build the loop.</h1><span>Frame-by-frame pixel animation with continuous playback, contextual teaching, and engine-ready output.</span><div class="actions"><a class="action big" href="#frames">Start drawing</a><a href="#out">Read the build sheet →</a></div><small>Local-first · no account · nothing uploaded</small></div>
			<div class="plan"><div class="plan-title"><b>WHITE CHICKEN / WALK CYCLE</b><span>REV B</span></div><div class="measure top"><i></i><span>16 PX</span></div><div class="measure side"><i></i><span>16 PX</span></div><div class="subject"><Sprite playing scale={18}/></div><div class="note n1"><i></i><span>COMB / INDEX 07</span></div><div class="note n2"><span>4 FRAME ASSEMBLY</span><i></i></div><div class="plan-foot"><span>RATE 08 FPS</span><span>CYCLE 500 MS</span><span>ALPHA 1 BIT</span></div></div>
		</section>

		<section id="frames"><div class="section-copy"><p>Detail A · frame bays</p><h2>Every drawing has a measured place.</h2><span>The loop keeps running while one bay changes. Spacing and holds remain visible, not deferred until export.</span></div><div class="bays">{#each {length:4} as _,i}<figure><header><b>F-{String(i+1).padStart(2,'0')}</b><span>{i===1?'160':'113'} MS</span></header><div><Sprite frame={i} scale={8}/></div><figcaption>16 × 16 / DB16</figcaption></figure>{/each}</div></section>

		<section class="views" id="views"><div class="section-copy"><p>Detail B · view schedule</p><h2>One document, three working plans.</h2><span>Frame, zoom, palette, and history persist between views. The schedule records both strength and blind spot.</span></div><div class="schedule"><div class="schedule-head"><span>Ref</span><span>View</span><span>Designed for</span><span>Not designed for</span></div>{#each VIEWS as [ref,name,great,bad]}<div><b>{ref}</b><strong>{name}</strong><span>{great}</span><em>{bad}</em></div>{/each}</div></section>

		<section class="revision"><b>REVISION T09</b><blockquote>Classic pixel animation often runs at 6–10 FPS. Smoothness comes from good in-betweens, not speed.</blockquote><p>Notes are triggered by relevant work, one at a time. Any note can be struck from the plan forever.</p></section>

		<section id="out"><div class="section-copy"><p>Sheet C · deliverables</p><h2>The build produces ordinary files.</h2><span>PNG sprite sheet, TexturePacker JSON, Doodle-Do project, GIF, or zipped frames. Phaser and Godot imports are verified.</span></div><div class="deliverables"><div><b>C1</b><span>SPRITE-SHEET.PNG</span><small>uniform frame grid</small></div><div><b>C2</b><span>ATLAS.JSON</span><small>engine metadata</small></div><div><b>C3</b><span>CHICKEN-WALK.DOODLEDO.JSON</span><small>owned project copy</small></div><div><b>C4</b><span>CHICKEN-WALK.GIF</span><small>motion proof</small></div></div></section>
	</main>
	<footer><strong>DOODLE-DO / DD-01</strong><p>PALETTE 16–64 · CANVAS 2D · STROKE → LOOP 0.1 MS P95</p><a class="action" href="#top">Open editor</a></footer>
</div>

<style>
	.plan-page{--blue:#124b69;--blue2:#0b3b55;--line:#b8d4df;--white:#f3f7f6;--red:#f05a4f;--yellow:#e7ce58;min-height:100%;background-color:var(--blue);background-image:linear-gradient(rgba(243,247,246,.055) 1px,transparent 1px),linear-gradient(90deg,rgba(243,247,246,.055) 1px,transparent 1px);background-size:32px 32px;color:var(--white);font:15px/1.55 'Martian Mono',monospace}a{color:inherit}header{display:flex;align-items:center;gap:2rem;padding:1rem clamp(1rem,5vw,5rem);background:var(--blue2);border-bottom:1px solid var(--line)}.mark{margin-right:auto;font-weight:800;text-decoration:none}.mark span{margin-left:.7rem;color:#a9c7d3;font-size:.58rem;font-weight:400}header nav{display:flex;gap:1.4rem}header nav a{color:#c5dae2;font-size:.65rem;text-decoration:none}.action{display:inline-flex;align-items:center;justify-content:center;min-height:40px;padding:.45rem 1rem;color:#102d3b;background:var(--white);border:2px solid var(--white);font-weight:800;text-decoration:none}.action:hover{color:#fff;background:var(--red);border-color:var(--red)}.action:focus-visible,a:focus-visible{outline:3px solid var(--yellow);outline-offset:2px}
	main,footer{width:min(1160px,calc(100% - 2rem));margin:auto}.hero{display:grid;grid-template-columns:minmax(280px,.75fr) minmax(500px,1.25fr);align-items:center;gap:clamp(3rem,8vw,8rem);min-height:720px;padding:4rem 0}.pitch>p,.section-copy>p{color:var(--red);font-size:.65rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.pitch h1{max-width:12ch;margin-top:1rem!important;font-family:Archivo,system-ui,sans-serif;font-size:clamp(3rem,5.3vw,5.2rem);line-height:.96;letter-spacing:-.04em;text-wrap:balance}.pitch>span{display:block;max-width:42ch;margin-top:1.5rem;color:#d0e0e5;font-family:Archivo,system-ui,sans-serif;font-size:1.05rem}.actions{display:flex;align-items:center;gap:1.2rem;margin-top:1.8rem}.actions>a:last-child{color:#fff;font-size:.72rem;text-decoration:none}.big{min-height:48px;padding:.65rem 1.2rem}.pitch small{display:block;margin-top:1.2rem;color:#a9c7d3;font-size:.6rem}
	.plan{position:relative;min-height:530px;border:2px solid var(--white);background:rgba(9,54,78,.38)}.plan-title,.plan-foot{display:flex;justify-content:space-between;padding:.7rem 1rem;border-bottom:1px solid var(--line);font-size:.62rem}.plan-foot{position:absolute;right:0;bottom:0;left:0;border-top:1px solid var(--line);border-bottom:0}.subject{display:grid;place-items:center;min-height:460px}.measure{position:absolute;display:flex;align-items:center;color:#c8dde5;font-size:.56rem}.measure i{display:block;border:1px solid var(--white)}.measure.top{top:55px;left:22%;right:22%;flex-direction:column;gap:.3rem}.measure.top i{width:100%;height:8px;border-bottom:0}.measure.side{top:22%;bottom:18%;left:1rem;flex-direction:row;gap:.4rem}.measure.side i{width:8px;height:100%;border-right:0}.note{position:absolute;display:flex;align-items:center;gap:.5rem;color:var(--red);font-size:.56rem}.note i{display:block;width:90px;height:1px;background:var(--red)}.n1{top:33%;right:1rem}.n2{bottom:23%;left:1.2rem}.n2 i{order:2}
	section:not(.hero){display:grid;grid-template-columns:minmax(230px,.55fr) minmax(470px,1fr);gap:clamp(2rem,8vw,7rem);padding:clamp(4rem,9vw,8rem) 0;border-top:1px solid var(--line)}.section-copy h2{max-width:14ch;margin-top:.8rem!important;font-family:Archivo,system-ui,sans-serif;font-size:clamp(2rem,3.5vw,3rem);line-height:1.05;letter-spacing:-.035em;text-wrap:balance}.section-copy>span{display:block;max-width:40ch;margin-top:1rem;color:#c8dbe2;font-family:Archivo,system-ui,sans-serif}
	.bays{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid var(--white);border-left:1px solid var(--white)}.bays figure{border-right:1px solid var(--white);border-bottom:1px solid var(--white)}.bays figure header{display:flex;justify-content:space-between;padding:.45rem;background:transparent;border-bottom:1px solid var(--line);font-size:.55rem}.bays figure>div{display:grid;place-items:center;aspect-ratio:1;background:rgba(7,45,65,.35)}.bays figcaption{padding:.4rem;color:#b8d1da;font-size:.52rem}
	.schedule{border-top:1px solid var(--white)}.schedule-head,.schedule>div{display:grid;grid-template-columns:50px 100px 1fr 1fr;gap:1rem;padding:.85rem .4rem;border-bottom:1px solid var(--line);font-size:.65rem}.schedule-head{color:#a9c7d3}.schedule b{color:var(--red)}.schedule em{color:#ffd0cc;font-style:normal}
	.revision{grid-template-columns:130px minmax(300px,1fr) minmax(180px,.4fr)!important;align-items:center;padding:2.5rem!important;background:var(--white);color:#12384b;border:0!important}.revision>b{color:#b9362f;font-size:.68rem}.revision blockquote{margin:0;font-family:Archivo,system-ui,sans-serif;font-size:1.3rem;line-height:1.35}.revision p{font-family:Archivo,system-ui,sans-serif;font-size:.8rem}
	.deliverables{border-top:1px solid var(--white)}.deliverables div{display:grid;grid-template-columns:45px 1.4fr 1fr;gap:1rem;padding:1rem .4rem;border-bottom:1px solid var(--line)}.deliverables b{color:var(--red)}.deliverables span{font-size:.68rem}.deliverables small{color:#b9d1da;font-size:.6rem}
	footer{display:flex;align-items:center;gap:1.5rem;padding:3rem 0 9rem;border-top:1px solid var(--line)}footer p{margin-right:auto!important;color:#b7cfd8;font-size:.58rem}
	@media(max-width:850px){.hero,section:not(.hero){grid-template-columns:1fr}.hero{min-height:0}.plan{margin-top:1rem}.revision{grid-template-columns:1fr!important}.schedule-head,.schedule>div{grid-template-columns:45px 90px 1fr 1fr}}
	@media(max-width:620px){header nav,.mark span{display:none}.plan{min-height:400px}.subject{min-height:340px}.note{display:none}.bays{grid-template-columns:repeat(2,1fr)}.schedule-head{display:none}.schedule>div{grid-template-columns:42px 1fr}.schedule span,.schedule em{grid-column:2}.deliverables div{grid-template-columns:38px 1fr}.deliverables small{grid-column:2}footer{flex-wrap:wrap}footer p{width:100%}}
</style>
