<script lang="ts">
	import { PALETTE } from '../sprites';
	import Sprite from '../Sprite.svelte';
	const TOOLS=[['Pencil','B'],['Eraser','E'],['Fill','G'],['Pick','I'],['Select','M'],['Lasso','L'],['Wand','W'],['Polygon','P']];
</script>

<div class="mock guide-shell">
	<header><strong>Doodle-Do</strong><span class="edition">Field desk</span><div class="modes"><button class="on">Focus <kbd>1</kbd></button><button>Grid <kbd>2</kbd></button><button>Loop <kbd>3</kbd></button></div><label>Specimen <input value="chicken-walk"/></label><span class="saved">Saved locally</span><div class="files"><button>New</button><button>Open</button><button class="save">Save</button><button>Export</button></div></header>
	<div class="toolbar"><div class="tools">{#each TOOLS as [name,key]}<button class:on={name==='Pencil'}>{name}<kbd>{key}</kbd></button>{/each}</div><label>Brush <select><option>2 px</option></select></label><button>Mirror</button><button>Flip H</button><button>Flip V</button><button class="onion">Onion</button><input type="range" value="35" aria-label="Onion opacity"/><span>35%</span></div>
	<div class="middle">
		<main><div class="plate"><div class="plate-id">PLATE 01 · FRAME 02</div><div class="canvas"><Sprite frame={1} scale={24} onion={0.35} grid/></div><div class="scale"><span>0</span><i></i><span>16 px</span></div></div><div class="status"><span><i class="prev"></i>Previous</span><span><i class="next"></i>Next</span><span>1-bit alpha</span><span class="zoom">− <b>1800%</b> +</span></div></main>
		<aside>
			<section><div class="section-head"><h2>Live observation</h2><span>8 fps</span></div><div class="preview"><Sprite playing scale={7}/></div><dl><div><dt>Frames</dt><dd>4</dd></div><div><dt>Cycle</dt><dd>500 ms</dd></div><div><dt>Range</dt><dd>01 → 04</dd></div></dl></section>
			<section><div class="section-head"><h2>Layers</h2><button>+</button></div><ul><li><button>●</button><span>highlights</span><button>•••</button></li><li class="active"><button>●</button><span>chicken</span><button>•••</button></li><li><button>○</button><span>rough</span><button>•••</button></li></ul><button class="wide">Merge down</button></section>
			<section><div class="section-head"><h2>Palette <small>16 / 64</small></h2><button class="locked">Locked</button></div><div class="palette"><button class="sw alpha" aria-label="Transparent"></button>{#each PALETTE as hex,i}<button class="sw" class:sel={i===15} style="background:{hex}" aria-label={hex}></button>{/each}</div></section>
		</aside>
	</div>
	<footer><div class="frame-head"><strong>Observed sequence</strong><button>New frame</button><button>Duplicate</button><button>Delete</button><span>Loop 01 → 04</span><label>Hold <input value="125"/> ms</label></div><ol>{#each {length:10} as _,i}<li><span>{String(i+1).padStart(2,'0')}</span><button class:current={i===1}>{#if i<4}<Sprite frame={i} scale={4}/>{:else}<b>+</b>{/if}</button></li>{/each}</ol></footer>
	<div class="note"><b>T02</b><p>The red ghost is your previous frame. Draw where things moved to, not where they were.</p><button>×</button></div>
</div>

<style>
	.guide-shell{--paper:#f4f5ef;--white:#fff;--ink:#1c2925;--forest:#183a30;--moss:#5d755f;--red:#a93630;--rule:#bdc8bd;--wash:#e5ebe2;display:flex;flex-direction:column;min-height:100vh;background:var(--paper);color:var(--ink);font:13px/1.4 Archivo,system-ui,sans-serif}button,input,select{min-height:29px;color:var(--ink);background:var(--white);border:1px solid var(--rule);border-radius:3px}button{padding:.25rem .55rem}button:hover{background:var(--wash)}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #d5c85d;outline-offset:1px}
	header{display:flex;align-items:center;gap:.7rem;min-height:54px;padding:.55rem .8rem;color:#f5f7f3;background:var(--forest)}header strong{font-family:Petrona,serif;font-size:1rem}.edition{color:#acc1b5;font-size:.65rem}.modes{display:flex}.modes button{color:#e9f0eb;background:transparent;border-color:#527065;border-radius:0;margin-left:-1px}.modes button:first-child{border-radius:3px 0 0 3px}.modes button:last-child{border-radius:0 3px 3px 0}.modes .on{color:#fff;background:var(--red);border-color:var(--red)}header label{display:flex;align-items:center;gap:.4rem;color:#b8c9bf;font-size:.68rem}header input{width:155px;padding:.35rem}.saved{margin-left:auto;color:#b8c9bf;font-size:.66rem}.files{display:flex;gap:.3rem}.save{color:#fff;background:var(--red);border-color:var(--red)}kbd{margin-left:.25rem;font-size:.56rem}
	.toolbar{display:flex;align-items:center;gap:.4rem;padding:.45rem .8rem;background:var(--wash);border-bottom:1px solid var(--rule);overflow-x:auto;white-space:nowrap}.tools{display:flex}.tools button{border-radius:0;margin-left:-1px}.tools button:first-child{border-radius:3px 0 0 3px}.tools button:last-child{border-radius:0 3px 3px 0}.tools .on,.onion{color:#fff;background:var(--forest);border-color:var(--forest)}.toolbar label{display:flex;align-items:center;gap:.3rem;color:#566860}.toolbar select{padding:.2rem}.toolbar input[type=range]{width:82px;accent-color:var(--red)}
	.middle{display:grid;grid-template-columns:minmax(420px,1fr) 260px;flex:1;min-height:470px}.middle main{display:flex;flex-direction:column;min-width:0;padding:1rem;background:#dce5dd}.plate{display:flex;flex-direction:column;width:min(72vh,650px);max-width:calc(100% - 2rem);aspect-ratio:1;margin:auto;background:#fff;border:1px solid var(--forest)}.plate-id{padding:.55rem .7rem;color:var(--red);border-bottom:1px solid var(--rule);font-size:.62rem;font-weight:700;letter-spacing:.1em}.canvas{display:grid;place-items:center;flex:1;overflow:hidden;background:repeating-linear-gradient(0deg,transparent 0 39px,rgba(24,58,48,.055) 39px 40px)}.scale{display:flex;align-items:center;gap:.5rem;padding:.45rem .7rem;color:#63756b;border-top:1px solid var(--rule);font-size:.58rem}.scale i{display:block;width:80px;height:5px;border:1px solid var(--forest);border-top:0}.status{display:flex;gap:1rem;padding:.5rem .25rem 0;color:#56685f;font-size:.66rem}.status i{display:inline-block;width:9px;height:9px;margin-right:.3rem;border-radius:2px}.prev{background:#d04648}.next{background:#6daa2c}.zoom{margin-left:auto}.zoom b{color:var(--ink);margin:0 .5rem}
	aside{background:var(--paper);border-left:1px solid var(--forest)}aside section{padding:.75rem;border-bottom:1px solid var(--forest)}.section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:.55rem}.section-head h2{font-family:Petrona,serif;font-size:.82rem}.section-head span,.section-head small{color:#63756b;font-size:.62rem}.section-head button{min-height:23px;padding:.1rem .35rem}.preview{display:grid;place-items:center;aspect-ratio:1.6;background:#fff;border:1px solid var(--rule)}dl{margin:0}dl div{display:flex;justify-content:space-between;padding:.3rem 0;border-bottom:1px solid var(--rule);font-size:.65rem}dt{color:#66786e}dd{margin:0;font-weight:700}aside ul{border-top:1px solid var(--rule)}aside li{display:grid;grid-template-columns:auto 1fr auto;align-items:center;padding:.3rem;border-bottom:1px solid var(--rule)}aside li.active{background:#dce8df}aside li button{min-height:22px;padding:.1rem .3rem;border:0;background:transparent;color:var(--forest)}.wide{width:100%;margin-top:.5rem}.locked{color:var(--red)!important}.palette{display:grid;grid-template-columns:repeat(6,1fr);gap:5px}.sw{aspect-ratio:1;min-height:0;padding:0;border-radius:2px}.alpha{background:repeating-conic-gradient(#c4cbc5 0 25%,#fff 0 50%) 0 0/8px 8px}.sw.sel{outline:2px solid var(--red);outline-offset:1px}
	footer{background:var(--paper);border-top:1px solid var(--forest)}.frame-head{display:flex;align-items:center;gap:.4rem;padding:.4rem .7rem;border-bottom:1px solid var(--rule)}.frame-head strong{font-family:Petrona,serif}.frame-head span{margin-left:auto;color:#5f7067}.frame-head label{color:#5f7067}.frame-head input{width:44px;padding:.2rem;text-align:right}footer ol{display:flex;gap:.45rem;padding:.45rem .7rem!important;overflow-x:auto}footer li{flex:0 0 58px;color:#5d7066;text-align:center;font-size:.58rem}footer li button{display:grid;place-items:center;width:58px;aspect-ratio:1;padding:0;background:#fff;border-radius:2px}footer li button.current{outline:2px solid var(--red);outline-offset:1px}footer li b{color:#91a097}
	.note{position:fixed;right:280px;bottom:154px;display:grid;grid-template-columns:auto minmax(240px,430px) auto;align-items:center;gap:.7rem;padding:.7rem .85rem;background:#fff;border:1px solid var(--forest)}.note b{color:var(--red);font-size:.65rem}.note p{font-size:.75rem}.note button{border:0;background:transparent}
	@media(max-width:900px){.middle{grid-template-columns:1fr}aside{display:grid;grid-template-columns:repeat(3,1fr);border-left:0;border-top:1px solid var(--forest)}.note{display:none}}
	@media(max-width:680px){header{flex-wrap:wrap}.edition,.saved,header label{display:none}.files{margin-left:auto}.files button:not(.save){display:none}.tools button:nth-child(n+5),.toolbar>button,.toolbar>label,.toolbar>input,.toolbar>span{display:none}.middle main{padding:.55rem}.plate{max-width:100%}.canvas :global(canvas){transform:scale(.84)}aside{grid-template-columns:1fr}.frame-head button:nth-of-type(n+2),.frame-head span{display:none}.status span:nth-child(3){display:none}}
</style>
